### ISSUE TITLE
Add tests for "new" and "start studio" commands

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/cli#106]
The `asyncapi new` and `asyncapi start studio` commands don't have tests. It would be great to test their functionality.

PS: To test `stdin`, have a look at https://stackoverflow.com/questions/56797392/oclif-prompt-testing.

**Comment by Samridhi-98** [comment]
![image](https://user-images.githubusercontent.com/54466041/152118870-3cf312f8-d744-421d-ad1a-37d8de6f7bf2.png)


@fmvilas  I am getting this error while setting up locally.

**Comment by fmvilas** [comment]
Would you mind submitting a pull request? It's hard to understand the problem like this 🙂

**Comment by Samridhi-98** [comment]
@Souvikns  The issue is partially fixed as the `start studio` PR #227 review is still pending.
Please review it as well 🙂
