### ISSUE TITLE
Enable new feature from Generator to support templates hosted as private packages

### ISSUE THREAD

**Issue by derberg** [asyncapi/cli#1081]
#### Reason/Context

We just released a new feature in Generator -> https://www.asyncapi.com/docs/tools/generator/using-private-template

#### Description

Would be great to enable new flags in `asyncapi generate fromTemplate` command that enable user to pass custom `registry.url` and specific authorization method, like `registry.auth` or `registry.token`

@Souvikns I think it is a nice, pretty simple new feature that would be good for onboarding potential new maintainer as it is typical enhancement to existing command - so maintainer candidate learns code from perspective of commands and their tests

**Comment by Shiva953** [comment]
would like to take this up!

**Comment by AayushSaini101** [comment]
@derberg Is it available to work, I can complete this

**Comment by derberg** [comment]
yeah, I guess so, @Shiva953 in related PR do not respons 2 weeks already

**Comment by AayushSaini101** [comment]
> yeah, I guess so, @Shiva953 in related PR do not respons 2 weeks already
Thanks @derberg

**Comment by AayushSaini101** [comment]
@Amzani @derberg Started working on it creating a draft PR
