### ISSUE TITLE
Studio started with AsyncAPI cli tools does not support version 3.0

### ISSUE THREAD

**Issue by lovebug356** [asyncapi/cli#1085]
When starting the AsyncAPI Studio from the cli tools. The instance complains on not supporting specification 3.0

Can be reproduced with creating a new file with the CLI tools and auto starting Studio:
```
asyncapi new file
? name of the file? asyncapi.yaml
? open in Studio? Yes
Created file asyncapi.yaml...
Studio is running at http://localhost:3210?liveServer=3210
Watching changes on file asyncapi.yaml
```

<img width="1174" alt="image" src="https://github.com/asyncapi/cli/assets/51261/591f5835-367b-45ee-a54a-a6ae005baed4">

Tested with:
```
$ asyncapi --version
@asyncapi/cli/1.3.3 darwin-arm64 node-v20.7.0
```

**Comment by derberg** [comment]
`@asyncapi/studio` dependency must be updated to latest version as it uses old 0.17 -> https://github.com/asyncapi/cli/blob/master/package.json#L22

@KhudaDad414 did you plan to bump? automated bump do not work as you did some monorepo stuff in studio repo so I bet standard autobump workflow do not work as expected anymore

**Comment by DavidSchmidt00** [comment]
They are already working on it, see https://github.com/asyncapi/cli/issues/629
