### ISSUE TITLE
Validate command output is polluted by noisy messages

### ISSUE THREAD

**Issue by cykl** [asyncapi/cli#1095]
#### Describe the bug

Validate command supports multiple diagnostics formats. 
I assume that formats like json or junit are intended to be processed by machines.

However, validate command standard output is a mix of the selected diagnostics format and informational messages. 
User must parse / filter standard output to end up with the expected file.

#### How to Reproduce

```
docker run -it --rm     -v ${PWD}:/spec test asyncapi validate /spec/docs/events/asyncapi.yaml --diagnostics-format=junit  > asyncapi.xml

cat asyncapi.xml
(node:1) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

File /spec/docs/events/asyncapi.yaml and/or referenced documents have governance issues.
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
<testsuite package="org.spectral" time="0" tests="1" errors="0" failures="1" name="/spec/docs/events/asyncapi.yaml">
<testcase time="0" name="org.spectral.asyncapi-document-resolved(#/channels/hems-site-events/messages/GatewayConnectionMqttDisconnected/payloa)" classname="/spec/docs/events/asyncapi"><failure message="Property &quot;payloa&quot; is not expected to be here"><![CDATA[line 94, col 16, Property "payloa" is not expected to be here (asyncapi-document-resolved) at path #/channels/site-events/messages/GatewayConnectionMqttDisconnected/payloa]]></failure></testcase>
</testsuite>
</testsuites>
```

#### Expected behavior

It would be nice to separate command logs from actual output. 
Those options could work:
 * Add an optional outputFile parameter 
 * Add an optional silent parameter

**Comment by Shurtu-gal** [comment]
Regarding silent parameter the current validate command already has a boolean flag `log-diagnostics`. The output file is a valid addition. Thanks for giving this idea 🤗

**Comment by Amzani** [comment]
still relevant

**Comment by dhruvilmehta** [comment]
Currently, it's printing the XML in the command line. XML file should contain the following that is printed in the terminal right? It should only contain pure XML and not the diagnostics logs, right?
![image](https://github.com/user-attachments/assets/320ccf0e-a34f-469c-945a-b9b2bebe9901)

**Comment by Shurtu-gal** [comment]
Yeah, output-file param will become more and more necessary as we do more UI/UX improvements.
WDYT @Amzani ?

**Comment by sushilpandeyy** [comment]
@Souvikns Could you please assign this issue to me? Thank you!
