### ISSUE TITLE
Add codeclimate diagnostics-format to validate command

### ISSUE THREAD

**Issue by cykl** [asyncapi/cli#1096]
#### Reason/Context

I would like to integrate the output of asyncapi validate to Gitlab's merge request. 

Gitlab supports [following artefact types](https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html). 
While both Gitlab and asyncapi supports Junit format, it's not the most suitable format for this task.
It would be preferable to use codeclimate.

#### Description

It would be nice add support of `codeclimate` to `validate --diagnastics-format`.

Code climate specification is available here:

-  https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool
-  https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types

Basic implementation should be easy and avoid users having to implement their own mapping steps.

For reference codeclimate support [has been added to redocly-cli 18 months ago](https://github.com/Redocly/redocly-cli/issues/650) for this exact purpose.

**Comment by Amzani** [comment]
That would be great indeed, however, we have a dependency on spectral and that would be challenging to support 
https://github.com/stoplightio/spectral/issues/2283
