### ISSUE TITLE
allow user to pick a template from the `new` command

### ISSUE THREAD

**Issue by boyney123** [asyncapi/cli#111]
#### Reason/Context
Please try answering few of those questions

At the moment the `new` command generates a basic AsyncAPI for the user, but it would be nice if we asked them some more questions like:

- What protocol would you like to use (MQTT, WebSockets, HTTP, None)
- Based on what they select it generates using the correct template.

## How will this change help?

I think just more flexibility for the CLI tool and give people more options, users will come from all backgrounds, giving them a helping hand with their chosen protocol might really help.

**Comment by boyney123** [comment]
Added code in #131

**Comment by derberg** [comment]
@boyney123 this one is implemented, right?

**Comment by boyney123** [comment]
Yeah merged part of #131 , will close 👍
