### ISSUE TITLE
Ability to score quality of async api specification file

### ISSUE THREAD

**Issue by Ferror** [asyncapi/cli#1131]
#### Reason/Context

Many optional yet valuable parameters in the Async API specification can improve the developer experience. Like `example`, `description`, `format`, etc. When working with many specifications, I was asked, "**How good is our documentation?**". How do I measure if my documentation is good, mediocre, insufficient, or 1-100?

I propose a new command like `score` or `evaluate` that will reuse existing warnings and errors from the `validate` command. The command will extend the list of best practices and generate some final/aggregated scores. Hints that will increase the score should be provided.

##### A couple of examples

1. if the specification has **servers**, then it increases the score
2. if the specification has **descriptions**, then it increases the score
3. if the specification has **examples**, then it increases the score
4. if the specification has a **format**, then it increases the score
5. if the specification has **channels**, then it increases the score
6. if the specification has **operations**, then it increases the score
7. if the specification has a **license**, then it increases the score

**Comment by AayushSaini101** [comment]
@Amzani I want to work on this issue:) I have worked similar kind of issue for Jekins https://github.com/jenkins-infra/plugin-health-scoring that provide scoring for each pluing on basis of some parameters

**Comment by Amzani** [comment]
Sure @AayushSaini101 please go ahead.
That's a nice feature to have as well in studio

**Comment by AayushSaini101** [comment]
> Sure @AayushSaini101 please go ahead. That's a nice feature to have as well in studio

@Amzani @derberg @Ferror We need to decide how much score we need to increase for particular parameter. Which parameter will be more proritise as compared to others, I can created a small proposal for that

**Comment by Ferror** [comment]
I think we could start with something simple in the form of MVP.

1. The abstraction for scorecards/metrics (What to score)
2. Each metric may have a scale/weight
3. Deciding on an algorithm to calculate the sum/mediana/average

Feel free to propose something. We could also start with linear calculation (without weights) 😄

**Comment by AayushSaini101** [comment]
> I think we could start with something simple in the form of MVP.
> 
> 1. The abstraction for scorecards/metrics (What to score)
> 2. Each metric may have a scale/weight
> 3. Deciding on an algorithm to calculate the sum/mediana/average
> 
> Feel free to propose something. We could also start with linear calculation (without weights) 😄


@Amzani @Ferror If we used the same scoring mechanism as Jenkins used on the 1800+ Plugins, this would be the structure: Reference: https://docs.google.com/document/d/1XT5O99-QEZadFZsMuXhzahvEmeL7-1H7HWpsnPLuMIk/edit#heading=h.cw0t6u8yvrcm here my proposal 

* New command structure: asyncapi evaluate <filename>

* there will be coefficient and score parameters, Coefficient will tell the weight of the particular parameter and score will be [0,1] the final score will be coefficient*score. 

Example: 

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-3162d09f-7fff-1565-c571-41cf97184267"><div dir="ltr" style="margin-left:0pt;" align="left">
Health Score | Plugin 1 | Plugin 2 | Plugin 3
-- | -- | -- | --
Score | (4.7*100)/totalParameters=24 | (6.8*100)/totalParameters=35 | (9*100)/totalParameters=47
</div><br /><br /><br /><p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial,sans-serif;color:#000c1a;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Health Scoring Categories for Percentage:&nbsp;</span></p><br /><p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial,sans-serif;color:#000c1a;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Level 1 [ Low Health ]:</span><span style="font-size:12pt;font-family:Arial,sans-serif;color:#000c1a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> 0-25%&nbsp;</span></p><br /><p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial,sans-serif;color:#000c1a;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Level 2 [ Medium Health]:</span><span style="font-size:12pt;font-family:Arial,sans-serif;color:#000c1a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> 25-75%</span></p><br /><p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial,sans-serif;color:#000c1a;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Level 3 [ Good Health]: </span><span style="font-size:12pt;font-family:Arial,sans-serif;color:#000c1a;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&gt;75%</span></p></b><br class="Apple-interchange-newline">

We can add lots of parameters like check whether the latest asyncapi version is used or not etc. We can create a poll to take the approval of the coeffiicent from the TSC Members using the voting that we created in community repo. :)

**Comment by Ferror** [comment]
TotalParameters will be based on async API schema, so it should be const. Quite simple and efficient ❤️ 

I'm not sure if the voting process would be IMO necessary, but feel free to create it 😄

**Comment by AayushSaini101** [comment]
> TotalParameters will be based on async API schema, so it should be const. Quite simple and efficient ❤️
> 
> I'm not sure if the voting process would be IMO necessary, but feel free to create it 😄

@Ferror Regarding the coefiicient value of different parameters, i guess we need suggestion from members, that's why i am thinking of creating vote

**Comment by Amzani** [comment]
@AayushSaini101 Great proposal ❤️ 
voting from TSC members is not necessary, only maintainers of this repo.
Could you run your proposal with some AsyncAPI files to see how it will look from user perspective?

**Comment by AayushSaini101** [comment]
> @AayushSaini101 Great proposal ❤️ voting from TSC members is not necessary, only maintainers of this repo. Could you run your proposal with some AsyncAPI files to see how it will look from user perspective?

Sure, I will create a draft PR tomorrow :)
