### ISSUE TITLE
CLI is unable to bundle spec V3 documents using bundle command 

### ISSUE THREAD

**Issue by Souvikns** [asyncapi/cli#1137]
#### Describe the bug

`ayncapi bundle` command does not support bundling spec v3 documents, running the command on v3 documents gives error 

```
Error: One of the files you tried to bundle is AsyncAPI v3 format, the bundle command does not support it yet, please checkout https://github.com/asyncapi/bundler/issues/133
```

#### How to Reproduce
To reproduce this error all you have to do is try to bundle an v3 spec using CLI. 

Run the following command to reproduce this error 
```
asyncapi bundle file-name
```

#### Expected behavior
`asyncapi bundle` command should be able to bundle Asyncapi V3 spec files.

**Comment by s1mrankaur** [comment]
+1.

**Comment by eshepelyuk** [comment]
Any news on this ?

**Comment by Amzani** [comment]
Mostly done by @Souvikns, he just needs to update some tests in https://github.com/asyncapi/cli/pull/1138
