### ISSUE TITLE
No file extension when user defines the name of the file (using new command)

### ISSUE THREAD

**Issue by boyney123** [asyncapi/cli#114]
#### Describe the bug

When user uses the `new` command they can provide the filename of the file.

For example, if I put `myNewFile` as a value, the file is created OK, but no file extension is added.

I think it might be a better experience if we detect if no extension is on the file and just put the `yaml` extension of the file for them?

**Comment by jjung99** [comment]
Hi, I would like to take a look at this issue

**Comment by boyney123** [comment]
Hey @jjung99 ,

Sorry I managed to find some time earlier and got a PR raised, but be good if you fancy having a look and review it? https://github.com/asyncapi/cli/pull/117

Or if you think of a better way to do it?

**Comment by jjung99** [comment]
It is fine! I just wanted to take a look at others' projects and try to fix a bug if any for learning purposes. Thanks for the comment!
