### ISSUE TITLE
[CLI] Measure AsyncAPI DX metrics

### ISSUE THREAD

**Issue by Amzani** [asyncapi/cli#1161]
Related to https://github.com/Amzani/asyncapi-metrics-dashboard/issues/5

After merging https://github.com/asyncapi/cli/pull/859, we need to track unique AsyncAPI Files and users, see https://github.com/Amzani/asyncapi-metrics-dashboard/issues/2

## Definition of done

- We expected to use the `.asyncapi-analytics` file to store user IDs (UUID v4 is perfect)
- We use SHA1 (FileName) for identifying AsyncAPI File Names
- Analytics documentation is updated to inform users about what we collect
- We don't impact CLI performance

Example of hardcoded values I've used for testing purpose in `base.ts`

```
async finally(error: Error | undefined): Promise<any> {
    await super.finally(error);
    this.metricsMetadata['success'] = error === undefined;
    this.metricsMetadata['user'] = 'c320a14b-37f7-4a44-bdf0-9bf3ec22b652';
    this.metricsMetadata['source'] = this.generateSHA1(this.specFile?.getSource() || '');
    console.log('getFileURL', this.specFile?.getSource(), 'hash', this.generateSHA1(this.specFile?.getSource() || ''));
    await this.recordActionFinished(this.id as string, this.metricsMetadata, this.specFile?.text());
  }

```

**Comment by peter-rr** [comment]
/progress 100
Tracking for unique AsyncAPI files and users already implemented.
