### ISSUE TITLE
CLI new UI/UX implementation

### ISSUE THREAD

**Issue by Amzani** [asyncapi/cli#1214]
## Problem

After https://github.com/asyncapi/cli/issues/872 completion, we now have a [visual direction](https://www.figma.com/file/9yt0aJh7cVoJHxXzDDb2lt/CLI-UI%2FUX-Project?type=design&node-id=195%3A762&mode=design&t=XeFNVy8nWiOjPVeC-1) of what needs to be implemented in the CLI.

## Scope

- [x] https://github.com/asyncapi/cli/issues/1215
- [x] #1379
- [x] #1381 
- [x] #1382 
- [x] #1385

**Comment by Shurtu-gal** [comment]
Great @Amzani, we can make some decisions in parallel too.

There was a great proposal by @fmvilas on new framework, [clack](https://github.com/natemoo-re/clack)

**Comment by Amzani** [comment]
Great @Shurtu-gal,
I don't know clack, does it replace oclif? 
In case we need to change Oclif, this might help https://github.com/asyncapi/server-api/issues/485#issuecomment-1961317382

**Comment by Shurtu-gal** [comment]
@Amzani I believe we can take it as a reference, and build our own design system to not face problems down the line.

**Comment by aeworxet** [comment]
### Bounty Issue's service comment

Text labels: `bounty/2024-Q2`, `bounty/advanced`, `bounty/coding`
First assignment to third-party contributors: [2024-03-22 00:00:00 UTC+12:00](https://time.lol/#2024-03-22T00:00:00+12:00)
End Of Life: [2024-08-31 23:59:59 UTC-12:00](https://time.lol/#2024-08-31T23:59:59-12:00)

@asyncapi/bounty_team

**Comment by utnim2** [comment]
would like to work on this

**Comment by Amzani** [comment]
@utnim2 @Shurtu-gal already started to work on the foundations, I think once he finish you can be part of it, as we need to implement DX in remaining commands.

**Comment by aeworxet** [comment]
@Amzani Please assign @Shurtu-gal and do not disperse the assignment, as unlike usual GitHub issues, the Bounty Issue can be worked on by only one person.

**Comment by Shurtu-gal** [comment]
@Amzani I was looking into this, and I am faced with some doubts:-
The current output looks something like:- 
![image](https://github.com/asyncapi/cli/assets/100484401/2933b659-5d02-4b98-a62a-49406fa1eff1)

And the updated one is like given [here](https://www.figma.com/file/9yt0aJh7cVoJHxXzDDb2lt/CLI-UI%2FUX-Project?type=design&node-id=195-364&mode=design&t=RYxnhn0v0IKMT3Rz-4)

- How are we supposed to get the docs link for a specific error?
- How are we supposed to intelligently pass on next step for the user?

**Comment by Shurtu-gal** [comment]
Also `clack/prompts` is not required I suppose as similar things are there in oclif. Of course I will try it once and see if it provides any benefits and check things out.

**Comment by Amzani** [comment]
@Shurtu-gal 

> How are we supposed to get the docs link for a specific error?
The warning/errors that you mention are coming from [spectral](https://github.com/stoplightio/spectral/blob/b93dbc88afbac3b4f4fffd46f499cb87aec1eea2/packages/rulesets/src/asyncapi/index.ts) and our [custom ruleset](https://github.com/asyncapi/parser-js/blob/58ae9387dd3d717af05debf8416deb1cac65bfd9/src/ruleset/v3/ruleset.ts#L5) @smoya you confirm ?

> How are we supposed to intelligently pass on next step for the user?
We can update the rulesets to inject the links, or do some magic with the parser, @smoya could have a better idea.

**Comment by smoya** [comment]
> @Shurtu-gal
> 
> > How are we supposed to get the docs link for a specific error?
> 
> The warning/errors that you mention are coming from [spectral](https://github.com/stoplightio/spectral/blob/b93dbc88afbac3b4f4fffd46f499cb87aec1eea2/packages/rulesets/src/asyncapi/index.ts) and our [custom ruleset](https://github.com/asyncapi/parser-js/blob/58ae9387dd3d717af05debf8416deb1cac65bfd9/src/ruleset/v3/ruleset.ts#L5) @smoya you confirm ?

Validation of v3 is done via some of the rules in https://github.com/asyncapi/parser-js/blob/58ae9387dd3d717af05debf8416deb1cac65bfd9/src/ruleset/ruleset.ts (those that are not filtered to apply exclusively to Spec v2) and https://github.com/asyncapi/parser-js/blob/58ae9387dd3d717af05debf8416deb1cac65bfd9/src/ruleset/v3/ruleset.ts, which are exclusive to Spec v3.

> 
> > How are we supposed to intelligently pass on next step for the user?
> 
> We can update the rulesets to inject the links, or do some magic with the parser, @smoya could have a better idea.

Not trivial at all. We would need to either modify each of the functions that validate to understand the errors and match with some kind of dictionary of links/solutions, or rather parse the final output with some regex or similar and match with link/solutions. ATM, I can't think on a really easy to do stuff.

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Advanced        |2024-03-27                 |[2024-04-01](https://time.lol/#2024-04-01T00:00:00+12:00)              |**[2024-05-24](https://time.lol/#2024-05-24T23:59:59-12:00)**        |[2024-04-19](https://time.lol/#2024-04-19T23:59:59-12:00)         |[2024-05-10](https://time.lol/#2024-05-10T23:59:59-12:00)         |**[2024-05-24](https://time.lol/#2024-05-24T23:59:59-12:00)**    |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR201) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR103).

**Comment by helios2003** [comment]
Hi @Amzani, I would like to work on the above-mentioned issues. Can you please assign them to me?

**Comment by helios2003** [comment]
I had an issue while testing the CLI, whenever I change any code in `src/commands/new/file.ts` for example build the project and run the asyncapi commands again, why isn't the new command displayed on the terminal? I checked and the correctly transpiled code is present in the ``./lib`` directory as well. Should I do something else as well along with this command?

**Comment by aeworxet** [comment]
@helios2003, the above issues are atomic tasks of this Bounty Issue which is already assigned to @shurtu-gal.

**Comment by aeworxet** [comment]
@helios2003, the above issues are atomic tasks of this Bounty Issue which is already assigned to @shurtu-gal, and he IS working on them.

**Comment by helios2003** [comment]
Oh okay, since the issues were opened individually I thought they were open for other contributors as well. Thanks for the clarification @aeworxet

**Comment by peter-rr** [comment]
> I had an issue while testing the CLI, whenever I change any code in `src/commands/new/file.ts` for example build the project and run the asyncapi commands again, why isn't the new command displayed on the terminal?

@helios2003 Could you be a bit more specific about this issue? Thanks :)

**Comment by helios2003** [comment]
Sure @peter-rr , so the issue I am experiencing is as follows:  <br />
When I make any changes in the files in the ``src`` directory (like making any changes to the prompts displayed to the user in the terminal) and run the command ``npm run build``, the project builds and the modified transpiled code resides in the ``./lib``  directory. After this when I try to run the required command, my custom prompts do not come appear the default prompts appear on the screen.  So is there something I am missing or how do I make it work?<br />
My general point is how do I view the changes I make in the CLI codebase myself?

**Comment by Shurtu-gal** [comment]
Hey @helios2003 are you using the `./bin/run` to run it?

**Comment by helios2003** [comment]
Yes @Shurtu-gal

**Comment by Shurtu-gal** [comment]
Could you share the link to your branch where the changed code resides?

Would be easier to get to the root from there.

**Comment by helios2003** [comment]
Hey @Shurtu-gal, this is the link to the branch https://github.com/helios2003/cli/tree/check-error. I made a few trivial changes to the prompts (for demonstration purposes) and even after following the steps I mentioned above, the changed prompts weren't visible on screen. Can you please check if you can reproduce the same error on your side?

**Comment by Shurtu-gal** [comment]
@Amzani all the commands have been migrated for which designs were provided.
I couldn't find designs for `optimize`, `config` and `start` command.

**Comment by helios2003** [comment]
@Shurtu-gal, I followed the required steps in my originally cloned repo, but the issue persisted. So, I decided to clone the project into a new path, and after setting it up, the problem disappeared, and it worked as expected. I suspect it may have been due to corruption along the particular path in my filesystem. Thanks a lot for the help, and my apologies for any inconvenience caused, as it turned out to be a local issue from my side.

**Comment by aeworxet** [comment]
@Shurtu-gal
If you have collected enough statistical information while doing PR https://github.com/asyncapi/cli/pull/1302 and PR https://github.com/asyncapi/cli/pull/1398 to understand in what direction the CLI commands' design goes, would you be able to do the rest of commands by yourself?
(new commands will be added over time anyway, so process for inheriting the design from the existing one needs to be developed in any case)

@Amzani
Would you agree with such an approach?

**Comment by Amzani** [comment]
@aeworxet yes, that was the initial idea to bootstrap the new DX direction and apply to the rest of commands.
We can even flag the remaining issues as `first-time-issues`

**Comment by aeworxet** [comment]
@Amzani 
Decide, please, to what extent this issue should be completed so both
- this Bounty Issue could be considered completed
- https://github.com/asyncapi/cli/issues/872 could be closed

**Comment by Amzani** [comment]
Ok @aeworxet let's close it and consider it done.

**Comment by aeworxet** [comment]
### Bounty Issue Completed 🎉

@Shurtu-gal, please go to the [AsyncAPI page on Open Collective](https://opencollective.com/asyncapi) and submit an invoice for `USD 400.00` with the expense title `Bounty cli#1214`, tag `bounty`, and full URL of this Bounty Issue in the description.
