### ISSUE TITLE
[CLI] Add 'source' metadata for metrics collected

### ISSUE THREAD

**Issue by peter-rr** [asyncapi/cli#1225]
### Why do we need this improvement?

We need to include `source` metadata as a unique identifier for every file handled in CLI when collecting metrics for the commands executed.

### How will this change help?

This change will allow us to measure the `Time to first API Design` metric as described [here](https://github.com/Amzani/asyncapi-metrics-dashboard/issues/2#issuecomment-1946098809).

### How could it be implemented/designed?

We need to consider two different issues we've found so far:

- The **hashing algorithm** to use: We should make a decision based on computational cost and security aspects according to New Relic requirements and also the recommendations from SonarCloud. Some research about algorithms like `md5`, `sha1` or `sha256` is needed.
- Find another way to calculate the `Time to first API Design` metric, or a different way to identify the source so it doesn't change between file creation and generation. See https://github.com/asyncapi/cli/pull/859#discussion_r1520842866

### Related issue(s)
Relates to https://github.com/asyncapi/cli/issues/1161

**Comment by KhudaDad414** [comment]
I have opened a PR that addresses this issue. it will collect the `birth timestamp` of the file that cli works on. IMO it solves the issue provides the best value and more insight into the file.
