### ISSUE TITLE
`asyncapi start studio --file=random-file-that-does-not-exisit` launches studio but then displays a message that the file cannot be watched

### ISSUE THREAD

**Issue by boyney123** [asyncapi/cli#128]
#### Describe the bug

If you run the command `asyncapi start studio --file=random-file-that-does-not-exist` (for a file that does not exist) the studio will continue to open (with default spec) and the terminal will give an error.

```
[Error: ENOENT: no such file or directory, open 'exampleasdadsads'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'random-file-that-does-not-exist'
}
```

I think it might be a better developer experience if we just failed and not launch the studio?

**Comment by ritik307** [comment]
@boyney123 @Souvikns I would be great so if no one is working on it I would like to take this issue.

**Comment by Souvikns** [comment]
Sure @ritik307 you can take up this issue, now is working on this as of now. 👍🏻

**Comment by ritik307** [comment]
@Souvikns I have doubts, how can I test my changes?

**Comment by Souvikns** [comment]
@ritik307 if you have written any test scripts you can just run `npm run test` and to run the CLI locally you can run run `./bin/run` and if this does not work for you try running `node ./bin/run`.
