### ISSUE TITLE
Add Time to First API Design DX metric

### ISSUE THREAD

**Issue by Amzani** [asyncapi/cli#1300]
## Why do we need this improvement?

After merging https://github.com/asyncapi/cli/pull/859 
[DX Working group](https://github.com/orgs/asyncapi/discussions/1099) would like to track [Time to First API Design](https://github.com/Amzani/asyncapi-metrics-dashboard/issues/2#issuecomment-1946098809)

## How will this change help?

Improve our tooling

## How could it be implemented/designed?

Check https://github.com/Amzani/asyncapi-metrics-dashboard/issues/2#issuecomment-1946098809
As the AsyncAPI filename might change between the creation (`asyncapi new file`) and generation (code, doc), we could try this solution described [here](https://stackoverflow.com/questions/43170582/is-there-any-way-to-retrieve-a-file-folders-unique-id-via-nodejs) - If this is not working then we could just use the filename as we don't need to deal with edge cases.

## Scope

- [x] https://github.com/Amzani/asyncapi-metrics-dashboard/issues/9
- [ ] https://github.com/Amzani/asyncapi-metrics-dashboard/issues/10

## 🚧 Breaking changes

No

## 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

## 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

## Are you willing to work on this issue?

No, someone else can work on it.

**Comment by KhudaDad414** [comment]
I want to work on this.

**Comment by peter-rr** [comment]
Same here! 😄

**Comment by KhudaDad414** [comment]
@peter-rr I have opened a PR here: #1304 would appreciate a review. 🙇

**Comment by KhudaDad414** [comment]
/progress 95

PR https://github.com/asyncapi/cli/pull/1304 is ready for review.
