### ISSUE TITLE
[FEATURE] Automatic Version Update Notification

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/cli#1371]
### Why do we need this improvement?

Right now, if you're using the CLI, there's no prompt telling you when a new version is available. This means you've got to keep an eye out yourself on GitHub or npm to make sure you're not missing out. 

Having to do this manually is a bit of a hassle and might lead to missing out on cool new features or important fixes.

### How will this change help?

Adding a little notification about new versions when you use the CLI could make a big difference. Users can get new features and bug fixes sooner.

### How could it be implemented/designed?

A few things to consider when implementing this:

- It should be automatic.
- Alert if a new version is available: If there’s a new version, the CLI should show a friendly message. Something like, "A new major/minor version is available. Update by running `npm update/upgrade -g @asycapi/cli`."
- The user should be able to disable it entirely.
- Frequency: Nobody likes a nag. We should make sure it only checks for updates/shows the message every so often (like once a week), so it's not annoying.

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

No, someone else can work on it.

**Comment by AayushSaini101** [comment]
@KhudaDad414 I want to work on this. I have some questions before: 
* Where we will get the notification message ? when the user install cli first time on their machine ? or when the user execute particular command using the cli ?

**Comment by KhudaDad414** [comment]
When the user runs a command.

Just like the 'npm' message when a new version is available.

**Comment by KhudaDad414** [comment]
When the user runs a command.

Just like the 'npm' message when a new version is available.
