### ISSUE TITLE
[BUG] File name is not captured while creating new asyncapi.yml from using new command 

### ISSUE THREAD

**Issue by AayushSaini101** [asyncapi/cli#1408]
### Describe the bug.

* After running following command:
` asyncapi new --example=tutorial.yml --no-tty `
* Getting following output:
Created file asyncapi.yaml...

### Expected behavior

The file name should be tutorial.yml

### Screenshots

<img width="601" alt="image" src="https://github.com/asyncapi/cli/assets/60972989/1f9a646f-14dd-48eb-b8cc-90f4d2c3b71b">

### How to Reproduce

* Use the latest version of CLI 
* Run the following command: 
 asyncapi new --example=tutorial.yml --no-tty

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by AayushSaini101** [comment]
Please verify this issue: cc @KhudaDad414 @derberg @Amzani

**Comment by AayushSaini101** [comment]
This is not an issue, i guess it would be good if we edit the doc here it is seems to confusing. 

`You can create a new asyncapi.yaml document by running: asyncapi new --example=tutorial.yml --no-tty.`

This should be:
` asyncapi new --file-name=asyncapi.yml --no-tty `

Reference: https://www.asyncapi.com/docs/tutorials/create-asyncapi-document

**Comment by Amzani** [comment]
@AayushSaini101 the documentation looks correct as `--example` is used for template selection, you can check `asyncapi new --help`
