### ISSUE TITLE
[FEATURE] New Command to format the Asyncapi document  [ Mentorship Project Part 2 ] 

### ISSUE THREAD

**Issue by AayushSaini101** [asyncapi/cli#1419]
### Why do we need this improvement?

Introducing new command that helps to format the asyncapi document with the help of CLI that help to reduce the errors as well as increase the readability of the document.

### How will this change help?

asyncapi format <documentName> the command helps to format the document 

### How could it be implemented/designed?

* Parse the Asyncapi document 
* Return the document with the proper formatting

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

Yes I am willing to submit a PR!

**Comment by Amzani** [comment]
Hi @AayushSaini101 could you provide some examples? Thanks

**Comment by AayushSaini101** [comment]
> Hi @AayushSaini101 could you provide some examples? Thanks

We have different formatter available that format the yml online: https://jsonformatter.org/yaml-formatter Here is one of its, 

@Amzani  one example
Before formatting:

<img width="533" alt="image" src="https://github.com/asyncapi/cli/assets/60972989/278e7c77-f7f1-46b9-82b5-7e1c1c2e2936">


After Formatting:
<img width="533" alt="image" src="https://github.com/asyncapi/cli/assets/60972989/b6da6f48-9724-44d6-9ec0-63969e780664">

**Comment by AayushSaini101** [comment]
Proposed Format of the command: 
asyncapi format asyncapi.yml --output <nameofthefile>
