### ISSUE TITLE
[FEATURE] Improve storage of `.asyncapi-analytics` config file

### ISSUE THREAD

**Issue by peter-rr** [asyncapi/cli#1427]
### Why do we need this improvement?

Main ideas taken from @asyncapi/developer_experience_wg  [slack discussion](https://asyncapi.slack.com/archives/C06G92DN05D/p1713226100765919):
cc @smoya @fmvilas 

1. We are handling the same analytics config file for [integration tests](https://github.com/asyncapi/cli/blob/master/test/integration/config/analytics.test.ts) and [source code](https://github.com/asyncapi/cli/blob/01f068a62de34d6deeb41d7f00b1ec2fd4b104d8/src/commands/config/analytics.ts#L21), which might lead to potential conflicts.

2. Also we are storing that analytics config file at home directory, which is not a recommended practice.

### How will this change help?

1. We can avoid potential conflicts by not mixing testing data with real user data.

2. Not polluting the user's home directory.

### How could it be implemented/designed?

1. Handling **different config files** for testing and source code.

2. The analytics config file should have a **configurable path**, and also be interchangeable between the different apps (like CLI, Studio), so we can know when the user is jumping from one app to another.

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

No, someone else can work on it.

**Comment by peter-rr** [comment]
@Amzani How can I add this issue to the DX working group's Kanban?

**Comment by Amzani** [comment]
@peter-rr it's automatically added

**Comment by peter-rr** [comment]
@fmvilas @smoya I'm trying to find out a good solution for what we talked about [here](https://asyncapi.slack.com/archives/C06G92DN05D/p1713226100765919), but I'm kind of stuck right now 🤔 

Regarding the usage of a configurable path for the analytics config file, should we interact with the user to get the file path desired and then use the value passed as a parameter? Could you provide any suggestion or example about this topic? Thanks, folks 😄

**Comment by smoya** [comment]
> @fmvilas @smoya I'm trying to find out a good solution for what we talked about [here](https://asyncapi.slack.com/archives/C06G92DN05D/p1713226100765919), but I'm kind of stuck right now 🤔
> 
> Regarding the usage of a configurable path for the analytics config file, should we interact with the user to get the file path desired and then use the value passed as a parameter? Could you provide any suggestion or example about this topic? Thanks, folks 😄

Let the path for the config file to be defined by an environment variable, with a default value in case is missing (the home directory is the default value). 
Despite the env var name (up to you), line https://github.com/asyncapi/cli/blob/master/src/base.ts#L101 could be changed to:

```ts
const analyticsConfigFile = process.env.ASYNCAPI_METRICS_CONFIG_PATH || join(homedir(), '.asyncapi-analytics'); 
```

Then, users could change the path by just setting such an env var. i.e.`ASYNCAPI_METRICS_CONFIG_PATH=/tmp/hello/.asyncapi-analytics`

Regarding tests, you can do the same: set up that env var to a known and controlled config file path instead of using the one located in ~home.
However, as I recommended in the Slack thread you shared, the best way to work with tests is to create an interface for the storage of the config, and swap it in tests (from in file, to in memory).

**Comment by peter-rr** [comment]
@Amzani We can proceed to close this issue since https://github.com/asyncapi/cli/pull/1451 and https://github.com/asyncapi/cli/pull/1452 are already merged 🚀
