### ISSUE TITLE
Add convert to AsyncAPI from Postman collection support

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/cli#1516]
As the PR was just merged, it's now possible to convert Postman collection to AsyncAPI v3, and it should be possible to do this through the CLI. Checkout https://github.com/asyncapi/converter-js?tab=readme-ov-file#postman-collection-to-asyncapi-conversion for how to do it.

https://github.com/asyncapi/converter-js/pull/276

**Comment by AayushSaini101** [comment]
I am on it : )

**Comment by Gmin2** [comment]
Hey @jonaslagoni as i have done #1498, i would like to take this

**Comment by AayushSaini101** [comment]
> Hey @jonaslagoni as i have done #1498, i would like to take this

@Gmin2 After discussion with @Souvikns we decided to submit this issue in the bounty program.  Please let me start working on this issue, if you have any doubt let me know thanks for cooperation

**Comment by ItshMoh** [comment]
@jonaslagoni  @Souvikns I want to take this issue. As i have made the specifications for conversion of postman collection into async api . I would love to work on this issue. Here is the [link](https://github.com/asyncapi/converter-js/pull/276) that pr.

**Comment by aeworxet** [comment]
### Bounty Issue's service comment

Text labels: `bounty/2024-Q4`, `bounty/medium`, `bounty/coding`
First assignment to regular contributors: [2024-09-20 00:00:00 UTC+12:00](https://time.lol/#2024-09-20T00:00:00+12:00)
End Of Life after: [2024-10-31 23:59:59 UTC-12:00](https://time.lol/#2024-10-31T23:59:59-12:00)

@asyncapi/bounty_team

##### The Bounty Program is not a Mentorship Program. The accepted level of Bounty Program Participants is **Middle**/**Senior**.
##### Regular contributors should explain in meaningful words how they are going to approach the resolution process when expressing a desire to work on this Bounty Issue.

**Comment by dhruvilmehta** [comment]
I can see that we can only export the Postman collection in a JSON file and not in a YAML file. In the Pull Request mentioned, it's converting YAML postman collection file to Async API file. @ItshMoh, Can you guide me on how we can export the Postman collection to a YAML file?

**Comment by aeworxet** [comment]
@dhruvilmehta
Bounty Issues are not collaborative work, and the Bounty Program is not a Mentorship Program. You are expected to be able to deliver the solution autonomously with only a little strategic guidance from the AsyncAPI Maintainer. Please describe how would **you** approach the resolution of this Bounty Issue, preferably [with a coding draft](https://github.com/asyncapi/converter-js/issues/233#issuecomment-2119226365).

**Comment by AayushSaini101** [comment]
@Gmin2 Will work on this issue, We have discussed it, and He has done the prerequisite task of this issue

**Comment by Gmin2** [comment]
We need to introduced a new option for `format` parameter named `postman`(as format was introduced in [this](https://github.com/asyncapi/cli/pull/1500/commits/e9126ddc7c733c18fee60c96035c6a5ae520dfb8) ), and then we need to also add `isPostmanCollection` in `convert.js` as introduced in [this](https://github.com/asyncapi/cli/pull/1500/commits/e9126ddc7c733c18fee60c96035c6a5ae520dfb8), and finally we need to add a testcase for it

I would like to work on this as part of bounty program

cc @aeworxet, @Souvikns

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Medium          |2024-09-21                 |[2024-10-07](https://time.lol/#2024-10-07T00:00:00+12:00)              |**[2024-11-17](https://time.lol/#2024-11-17T23:59:59-12:00)**        |[2024-10-20](https://time.lol/#2024-10-20T23:59:59-12:00)         |[2024-11-03](https://time.lol/#2024-11-03T23:59:59-12:00)         |**[2024-11-17](https://time.lol/#2024-11-17T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR224) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR99).

**Comment by aeworxet** [comment]
Does the code work as expected after the merge of https://github.com/asyncapi/cli/pull/1527?

**Comment by Gmin2** [comment]
> Does the code work as expected after the merge of #1527?

[Screencast from 03-10-24 04:31:19 PM IST.webm](https://github.com/user-attachments/assets/baca0ea7-011b-49a2-926c-edaac6074991)

**Comment by aeworxet** [comment]
@Souvikns, as the AsyncAPI Maintainer, who was responsible for the resolution of this Bounty Issue from the AsyncAPI's side, please confirm its technical resolution.

**Comment by Souvikns** [comment]
I confirm that this bounty issue is resolved succesfully.

**Comment by aeworxet** [comment]
### Bounty Issue Is Completed 🎉

@Gmin2 (`githubID` [127925465](https://api.github.com/user/127925465)), please go to the [AsyncAPI page on Open Collective](https://opencollective.com/asyncapi) and submit an invoice for `USD 200.00` with the expense title `Bounty cli#1516`, tag `bounty`, and full URL of this Bounty Issue in the description.
