### ISSUE TITLE
[FEATURE] Migrate to @oclif/core v4

### ISSUE THREAD

**Issue by Amzani** [asyncapi/cli#1520]
### Why do we need this improvement?

Use the new features of @oclif/core V4
https://github.com/oclif/core/releases/tag/4.0.0

### How will this change help?

- Code maintenance
- Have an updated CLI
- Deprecate `ux` module

### How could it be implemented/designed?

- Check that we don't have any breaking change, especially the `ux` module (e.g ux.prompt is removed in v4)

### 🚧 Breaking changes

Yes

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

No, someone else can work on it.

**Comment by Shurtu-gal** [comment]
@Amzani submitting this for the bounty program.

**Comment by Souvikns** [comment]
@Shurtu-gal can I work on this?

**Comment by aeworxet** [comment]
### Bounty Issue's service comment

Text labels: `bounty/2024-Q4`, `bounty/medium`, `bounty/coding`
First assignment to regular contributors: [2024-09-20 00:00:00 UTC+12:00](https://time.lol/#2024-09-20T00:00:00+12:00)
End Of Life after: [2024-10-31 23:59:59 UTC-12:00](https://time.lol/#2024-10-31T23:59:59-12:00)

@asyncapi/bounty_team

##### The Bounty Program is not a Mentorship Program. The accepted level of Bounty Program Participants is **Middle**/**Senior**.
##### Regular contributors should explain in meaningful words how they are going to approach the resolution process when expressing a desire to work on this Bounty Issue.

**Comment by aeworxet** [comment]
@Souvikns says,

> @Shurtu-gal I would like to work on this issue.

https://github.com/asyncapi/cli/issues/1520#issuecomment-2348055703

**Comment by Shurtu-gal** [comment]
Assigning to @Souvikns.

**Comment by aeworxet** [comment]
@Souvikns is an AsyncAPI Maintainer specified in https://raw.githubusercontent.com/asyncapi/community/master/MAINTAINERS.yaml, so they fall under the first category in the [prioritization list](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR27).

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Medium          |2024-09-17                 |[2024-10-07](https://time.lol/#2024-10-07T00:00:00+12:00)              |**[2024-11-17](https://time.lol/#2024-11-17T23:59:59-12:00)**        |[2024-10-20](https://time.lol/#2024-10-20T23:59:59-12:00)         |[2024-11-03](https://time.lol/#2024-11-03T23:59:59-12:00)         |**[2024-11-17](https://time.lol/#2024-11-17T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR224) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR99).

**Comment by aeworxet** [comment]
@Shurtu-gal
Please confirm the completion of this Bounty Issue.

**Comment by Shurtu-gal** [comment]
@aeworxet this issue is still in progress I believe. ref: #1555

**Comment by Shurtu-gal** [comment]
@aeworxet this issue is completed and everything is is place.

**Comment by aeworxet** [comment]
### Bounty Issue Is Completed 🎉

@Souvikns (`githubID` [41781438](https://api.github.com/user/41781438)), please go to the [AsyncAPI page on Open Collective](https://opencollective.com/asyncapi) and submit an invoice for `USD 200.00` with the expense title `Bounty cli#1520`, tag `bounty`, and full URL of this Bounty Issue in the description.
