### ISSUE TITLE
Description missing for the start command 

### ISSUE THREAD

**Issue by AayushSaini101** [asyncapi/cli#1534]
### Why do we need this improvement?

The description for the start command is missing 

### How will this change help?

Help to understand the start command properly of the asyncapi cli 

### Screenshots

<img width="920" alt="Screenshot 2024-09-30 at 3 15 21 PM" src="https://github.com/user-attachments/assets/34ab941e-b7e3-4fd6-8790-caadaf950e1e">

### How could it be implemented/designed?

Add description of the command .

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

None

**Comment by bandantonio** [comment]
I would like to take care of this issue. Please assign it to me.

**Comment by AayushSaini101** [comment]
@bandantonio You can start thanks : )
