### ISSUE TITLE
[BUG] Very out of date package JSON, breaking documentation example.

### ISSUE THREAD

**Issue by ghost** [asyncapi/cli#1562]
### Describe the bug.

The documentation example https://www.asyncapi.com/tools/generator is to run using:
```
docker run --rm -it --user=root -v ${PWD}/example:/app/example -v ${PWD}/output:/app/output \
asyncapi/cli generate fromTemplate https://bit.ly/asyncapi @asyncapi/html-template -o example
```

However, the versions in the `asyncapi/cli:2.8.0` (and many others) are out of date: [package.json](https://github.com/asyncapi/cli/blob/master/package.json).
```
{
  "name": "@asyncapi/cli",
  "description": "All in one CLI for all AsyncAPI tools",
  "version": "2.8.0",
  "author": "@asyncapi",
  "bin": {
    "asyncapi": "./bin/run_bin"
  },
  "bugs": "https://github.com/asyncapi/cli/issues",
  "dependencies": {
    "@asyncapi/avro-schema-parser": "^3.0.23",
    "@asyncapi/bundler": "^0.6.3",
    "@asyncapi/converter": "^1.6.2",
    "@asyncapi/diff": "^0.4.1",
    "@asyncapi/generator": "^1.17.25",
```

resulting in the following errors:

```
◑  Generation in progress. Keep calm and wait a bit..Template @asyncapi/html-template successfully installed in /usr/local/lib/node_modules/@asyncapi/cli/node_modules/@asyncapi/generator/node_modules/@asyncapi/html-template.
Version of used template is 3.0.0.
◇  Generation failed
Generator Error: This template is not compatible with the current version of the generator (1.17.25). This template is compatible with the following version range: >=2.0.0 <3.0.0.
```

### Expected behavior

Working example from homepage

### Screenshots

![image](https://github.com/user-attachments/assets/c9e9e485-28f2-4dd2-8e3e-ed2d747c1563)

### How to Reproduce

Run the example from the homepage: https://www.asyncapi.com/tools/generator

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by dk-coligo** [comment]
For example, current generator version is: 2.4.1 https://github.com/asyncapi/generator/releases

**Comment by bernarth** [comment]
The error `Generator Error: This template is not compatible with the current version of the generator (1.17.25). This template is compatible with the following version range: >=2.0.0 <3.0.0.` is happening to me as well. I think the latest version of the generator should be used instead ( [current version here](https://github.com/asyncapi/generator?tab=readme-ov-file) ) which is 2.5.0 today

**Comment by abiola-deimos** [comment]
Does anyone know what the workaround is?

**Comment by bernarth** [comment]
I am using `html-template` so, I am using an specific version of it. -> `2.3.14`
With the example above it could be something like: `docker run --rm -it --user=root -v ${PWD}/example:/app/example -v ${PWD}/output:/app/output \
asyncapi/cli generate fromTemplate https://bit.ly/asyncapi @asyncapi/html-template@2.3.14 -o example`

You can use a compatible version if you are using `html-template` [here](https://github.com/asyncapi/html-template/releases)

**Comment by yenidunya** [comment]
> The error `Generator Error: This template is not compatible with the current version of the generator (1.17.25). This template is compatible with the following version range: >=2.0.0 <3.0.0.` is happening to me as well. I think the latest version of the generator should be used instead ( [current version here](https://github.com/asyncapi/generator?tab=readme-ov-file) ) which is 2.5.0 today

tried changing it in package.json and then installing cli. installed version of the generator seems OK but then I received following error while using generate:

```
    return oclifHandler(err.message);
           ^

TypeError: oclifHandler is not a function
```

**Comment by bernarth** [comment]
I tried the same. But, when installing the CLI it comes with an older version of the installed packages which causes conflicts.

**Comment by yenidunya** [comment]
using the option --use-new-generator while generate overcomes the problem

**Comment by alsofr** [comment]
I'm running into a similar issue when running asyncapi generate with the latest version (2.11.1) of asyncapi install.
No docker involved, just a simple command line argument. I've tried install via brew or via pkg, with the current or with an older version, and I'm still getting the same error:

```
asyncapi generate golang -packageName=model my-asynapi-file.json -o model.go

/opt/homebrew/Cellar/asyncapi/2.11.1/libexec/lib/node_modules/@asyncapi/cli/bin/run_bin:12
    return oclifHandler(err.message);
           ^

TypeError: oclifHandler is not a function
    at /opt/homebrew/Cellar/asyncapi/2.11.1/libexec/lib/node_modules/@asyncapi/cli/bin/run_bin:12:12
```

Looking at [the code](https://github.com/asyncapi/cli/blob/31330bc4216e48d7d05da3fe60b41a21c4ba5570/bin/run#L9), the problem seems to be linked to a problem loading @oclif/core/handle.

```
const oclif = require('@oclif/core');

oclif.run()
  .then(require('@oclif/core/flush'))
  .catch((err) => {
    const oclifHandler = require('@oclif/core/handle');
    return oclifHandler(err.message);
  });
```

However,  things look consistent in the package.json:

<img width="549" alt="image" src="https://github.com/user-attachments/assets/24ac0d3b-d56b-40c6-9c2c-c64166d4bf5a">

**Comment by Shurtu-gal** [comment]
Hello, people just to put some context here to keep backward compatibility we are currently maintaining two versions of generator currently:- [2.4.1](https://github.com/asyncapi/cli/blob/master/package.json#L31) and [1.7.25](https://github.com/asyncapi/cli/blob/d4c67e2860e8521569f02a5f403d2d23833fd8df/package.json#L15).

So, to use templates requiring newer version please use the flag `--use-new-generator` as mentioned [here](https://github.com/asyncapi/cli/blob/d4c67e2860e8521569f02a5f403d2d23833fd8df/package.json#L15)

**Comment by alsofr** [comment]
Hi @Shurtu-gal , could you please explain how to use this flag with the `asyncapi generate golang` command? The flag doesn't seem to have any effect there

**Comment by Shurtu-gal** [comment]
> Hi @Shurtu-gal , could you please explain how to use this flag with the `asyncapi generate golang` command? The flag doesn't seem to have any effect there

This command is there for generating models and uses modelina under the hood. So this flag doesn't make sense there.

Could you specify your problem?

**Comment by alsofr** [comment]
I mentioned it a bit earlier 
https://github.com/asyncapi/cli/issues/1562#issuecomment-2510642166

Sorry for piggy-backing on this issue, the error message was the same so I assumed the issues must be related.

If the `--use-new-generator` flag is only for the `fromTemplate` mode, how do I fix the `generate` problem?

**Comment by Shurtu-gal** [comment]
> I mentioned it a bit earlier [#1562 (comment)](https://github.com/asyncapi/cli/issues/1562#issuecomment-2510642166)
> 
> Sorry for piggy-backing on this issue, the error message was the same so I assumed the issues must be related.
> 
> If the `--use-new-generator` flag is only for the `fromTemplate` mode, how do I fix the `generate` problem?

The command should be `asyncapi generate models golang -packageName=model my-asynapi-file.json -o model.go`

**Comment by alsofr** [comment]
Thanks!, I was missing the "models" keyword!  :)

**Comment by Shurtu-gal** [comment]
Closing this issue then. Feel free to open it and comment in case any thing is still unresolved.
