### ISSUE TITLE
[📑 Docs]: Update the documentation about the pretty command in the CLI

### ISSUE THREAD

**Issue by AayushSaini101** [asyncapi/cli#1577]
### What Dev Docs changes are you proposing?

After introducing the https://github.com/asyncapi/cli/pull/1549 new command that is asyncapi format the docs has not updated need to update the docs to understand more better about the command usage.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SahilDahekar** [comment]
Hey @AayushSaini101 , Can I work on this issue ?

**Comment by SahilDahekar** [comment]
@AayushSaini101 I can see the docs for the format command present on both website and docs folder on github. Is there any other specfic place left to update the docs for this command.

![image](https://github.com/user-attachments/assets/155b080b-ec54-4517-9036-a12c0e67fcb6)
![image](https://github.com/user-attachments/assets/57084e55-9b48-4dfa-ae86-e0ef6252e7cb)

**Comment by AayushSaini101** [comment]
@SahilDahekar I updated the command naming you can create a PR to write usage of the command thanks. Reference: https://github.com/asyncapi/cli/pull/1573
