### ISSUE TITLE
Workflow `.github/workflows/test-action.yml` needs urgent update before end of January 2025

### ISSUE THREAD

**Issue by derberg** [asyncapi/cli#1597]
workflow: https://github.com/asyncapi/cli/blob/master/.github/workflows/test-action.yml

reason:

```
GitHub
Artifact actions v3 will be closing down by January 30, 2025. You are receiving this email because you have GitHub Actions workflows using v3 of [actions/upload-artifact](https://app.github.media/e/er?s=88570519&lid=6648&elqTrackId=867ac6c9fa524bda9764f13bec8f8014&elq=49830aa2044d4416a4a36a4fbb961619&elqaid=4286&elqat=1&elqak=8AF5D94B629B77D0B2E640E5D18BB16F1795C5AC9FBBABD9859ACC84B62448387E12) or [actions/download-artifact](https://app.github.media/e/er?s=88570519&lid=6647&elqTrackId=bb54934dfd8c4c44b0e64ec2f2ba4824&elq=49830aa2044d4416a4a36a4fbb961619&elqaid=4286&elqat=1&elqak=8AF57B355AADDDE608896B61A68B985ADA84C5AC9FBBABD9859ACC84B62448387E12). After this date using v3 of these actions will result in a workflow failure. Artifacts within their retention period will remain accessible from the UI or REST API regardless of the version used to upload.

To raise awareness of the upcoming removal, we will temporarily fail jobs using v3 of actions/upload-artifact or actions/download-artifact. Builds that are scheduled to run during the brownout periods will fail. The brownouts are scheduled for the following dates and times:

January 9th, 12pm - 1pm EST
January 16th, 10am-2pm EST
January 23rd, 9am-5pm EST
What you need to do
Update workflows to begin using v4 of the artifact actions as soon as possible. While v4 improves upload and download speeds by up to 98% and includes several new features, there are [key differences](https://app.github.media/e/er?s=88570519&lid=6646&elqTrackId=e5ab3eaa455c4e8baa6af6be9fdb5c62&elq=49830aa2044d4416a4a36a4fbb961619&elqaid=4286&elqat=1&elqak=8AF58F0002C617A8A55C9135F66B95938105C5AC9FBBABD9859ACC84B62448387E12) from previous versions that may require updates to your workflows. Please see [the documentation](https://app.github.media/e/er?s=88570519&lid=6645&elqTrackId=af6fe6939f7e4dcba105e35734b7e6a0&elq=49830aa2044d4416a4a36a4fbb961619&elqaid=4286&elqat=1&elqak=8AF5780CABD5F82033875E5CE3EF4DF2FDFCC5AC9FBBABD9859ACC84B62448387E12) in the project repositories for guidance on how to migrate your workflows.
```

more info:
- https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes
- https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md

**Comment by Sahil-Shadwal** [comment]
@derberg can I work on this ?

**Comment by derberg** [comment]
I think so, probably @Shurtu-gal will need to help. I don't know, I just reported it as I got a notification from GH as org admin

**Comment by Shurtu-gal** [comment]
I looked into the **breaking changes** and migration docs. We are not using any of those features, hence our bump is as simple as changing `v3 -> v4`

@Sahil-Shadwal if you want you can take up this issue. 

> [!IMPORTANT] 
> You have to bump both `actions/upload-artifact` as well as `actions/download-artifact`

**Comment by IITI-tushar** [comment]
@Shurtu-gal @derberg I would like to work on this issue. Should I for the issue to get assign or start working on it?

**Comment by Shurtu-gal** [comment]
We don't assign issues here as it can be blocking. Anybody is free to work on the issue and submit PRs

**Comment by IITI-tushar** [comment]
OK, I will try to submit a PR soon.

**Comment by Shurtu-gal** [comment]
Okay, found a problem. They are not allowing multiple downloads also I suppose, although it is nowhere mentioned.

Filed an issue: https://github.com/actions/download-artifact/issues/369

cc: @derberg

**Comment by jalajk3004** [comment]
@Shurtu-gal kindly review my pull request https://github.com/asyncapi/cli/pull/1604

**Comment by Shurtu-gal** [comment]
Updates: I was dumb enough to not notice that @Sahil-Shadwal's PR #1601 didn't have v4 in all download-artifacts. Updated it and everything is working fine closing this issue.
