### ISSUE TITLE
Improve help message with list of available examples

### ISSUE THREAD

**Issue by derberg** [asyncapi/cli#162]
#### Reason/Context
Doing `asyncapi new --file-name=asyncapi.yml --example=default-example.yaml --no-tty` us super cool, but to get `default-example.yaml` you need to navigate to CLI installation, go into `assets/examples` and see the list of examples, or check if they will be listed in the interactive mode. You also need to kind of guess if example name is just the file name or filename with its extension.

So great feature is kind of hidden from users.

#### Description

Now I get:
```
$  asyncapi new --help

creates a new asyncapi file

USAGE
  $ asyncapi new

OPTIONS
  -e, --example=example      name of the example to use
  -h, --help                 show CLI help
  -n, --file-name=file-name  name of the file
  -p, --port=port            port in which to start Studio
  -s, --studio               open in Studio
  --no-tty                   do not use an interactive terminal
```

I should get:
```
$  asyncapi new --help

creates a new asyncapi file

USAGE
  $ asyncapi new

OPTIONS
  -e, --example=example.fileExtension      name of the example to use. Available examples are:
                                                - default-example.yml
                                                - somethingElseWithSpecificProtocol.json (MQTT)
  -h, --help                 show CLI help
  -n, --file-name=file-name  name of the file
  -p, --port=port            port in which to start Studio
  -s, --studio               open in Studio
  --no-tty                   do not use an interactive terminal
```

Bonus would be to see also example for `asyncapi new` at the bottom of help like:
```
EXAMPLES
  asyncapi new               start creation of a file in interactive mode
  asyncapi new --file-name=my-asyncapi.yml --example=default-example.yml --no-tty        create new file with specific name, using one of examples and without interactive emode

**Comment by derberg** [comment]
@LakshyaSatpal we do not practice issues assignment here. I mean we do not look at the assignment field. Just enough you wrote a comment that you are interested in the issue. So nobody else should now kick in with separate implementation, they should ask in the issue first

**Comment by LakshyaSatpal** [comment]
Oh, okay fine.

**Comment by derberg** [comment]
It was almost completed but the initial contributor is no longer active.

If anyone can pick up the work from https://github.com/asyncapi/cli/pull/320 that would be awesome. 95% of stuff is already done
