### ISSUE TITLE
Add `asyncapi optimize` command

### ISSUE THREAD

**Issue by derberg** [asyncapi/cli#218]
> This issue is for https://www.openforce.tech/ participants. If you do not participate in this even please pick up other issue from this repo, there is plenty of help needed 😄 

#### Reason/Context

We need to enable the community to use all AsyncAPI tools in CLI if only possible -> https://github.com/asyncapi/optimizer

#### Description

- add new command `asyncapi optimize` that uses https://github.com/asyncapi/optimizer and enable users to optimize single AsyncAPI file
- user should be able to pass one files to the optimizer `asyncapi optimize <context/filepath/url>` (getting file from context or filepath or URL is already provided in  CLI, you just use `load` function)
- by default it would optimize the document and print to the terminal, but user should be able to specify to get only the report, with flag `--report`
- by default full optimization is done, but user should be able to specify `--rules` where user can provide rules that should be applied by optimizer

> This issue is for https://www.openforce.tech/ participants. If you do not participate in this even please pick up other issue from this repo, there is plenty of help needed 😄 

@KhudaDad414 pinging you so you are aware 😄

**Comment by alceil** [comment]
Hey @derberg , I am Ashish Tom, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by KhudaDad414** [comment]
@alceil that's great. If you have any problems or questions regarding the tool itself, please do let me know.

**Comment by alceil** [comment]
Thanks @KhudaDad414

**Comment by alceil** [comment]
@KhudaDad414 any type of similar command I can refer too?

**Comment by alceil** [comment]
Hey @KhudaDad414 I have raised a pull request. Could you please review it?
