### ISSUE TITLE
Add `asyncapi bundle` command

### ISSUE THREAD

**Issue by derberg** [asyncapi/cli#219]
> This issue is for https://www.openforce.tech/ participants. If you do not participate in this even please pick up other issue from this repo, there is plenty of help needed 😄 

#### Reason/Context

We need to enable the community to use all AsyncAPI tools in CLI if only possible -> https://github.com/asyncapi/bundler

#### Description

- add new command `asyncapi bundle` that uses https://github.com/asyncapi/bundler and enable users to bundle multiple AsyncAPI files into one
- user should be able to pass multiple files to the bundler `asyncapi bundler <context-1/filepath1/url1> <context-2/filepath2/url2> <context-3/filepath3/url>3` (getting file from context or filepath or URL is already provided in  CLI, you just use `load` function)

> This issue is for https://www.openforce.tech/ participants. If you do not participate in this even please pick up other issue from this repo, there is plenty of help needed 😄 

@Souvikns pinging you so you are aware 😄

**Comment by ravikrshn** [comment]
I would like to work on this issue.

**Comment by AMANKANOJIYA** [comment]
I would like to work on this issue as part of Openforce 2022

**Comment by sudoshreyansh** [comment]
I want to work on this issue as part of OpenForce 2022

**Comment by amanbedi1** [comment]
HI @derberg I am Amanpreet  a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you.

**Comment by amanbedi1** [comment]
I just want to ask in this command the first file passed to command should be  base file or not.

**Comment by Souvikns** [comment]
> I just want to ask in this command the first file passed to command should be base file or not. 

`bundler` takes an array of files but it does not read the files, so you have to read and pass in the content. And `base` is an option that you can pass. `base` is for when you want to preserve some `schema` objects while you are merging multiple separate specifications. 



> and there should also be an option like --output that user could use to specify where to output bundled doc as a file. Thoughts? 

Yeah actually when `bundler` had a CLI it had a `--output` but since it is library now it just returns a document object and in the CLI interface we can implement the `--output`. My thought behind this was since `server-api` will also integrate `bundler` it would be easier to just bundler and then send the final document over REST.

**Comment by amanbedi1** [comment]
Ok so I think I just have to output bundled file in terminal or ```--output```  flag  specify where to output bundled doc as a file.
I will try to resolve it.

**Comment by derberg** [comment]
> My thought behind this was since server-api will also integrate bundler it would be easier to just bundle and then send the final document over REST.



what do you mean @Souvikns

**Comment by Souvikns** [comment]
I mean there is no way to output a file to a certain directory right now in `bundler`. It just gives you string and JSON object. So bundler does not care about file system so tools like `studio` where we do not have access to the file system can also use `bundler` same goes for `server-api` which will just send the data over HTTP request.

**Comment by derberg** [comment]
but this is CLI where we implement `bundler` option, so CLI should handle the option to output bundler-provided data into a file. Same like `server-api` will handle sending reply with JSON object. As you wrote, bundler is just to bundle and provide JSON Object (or string) and tools that integrate it, like CLI or Studio or server-api handle rest, like post processing of bundler output. 

we just need to remember that this `--output` flag just like `--watcher` should be generic, reusable, so other commands can easily use it too, like `diff` for example

**Comment by Souvikns** [comment]
> we just need to remember that this --output flag just like --watcher should be generic, reusable, so other commands can easily use it too, like diff for example

Oh now I get you 😄, yeah definitely `--output` should be reusable.

**Comment by amanbedi1** [comment]
Hey @derberg @Souvikns I am almost done with bundle command but there is a problem when I try to bundle below files the output is not as expected. So can you guide me how to do this. Files are attached below.

signup.yaml
``` 
asyncapi: '2.2.0'
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user Signup 

channels:
  user/signedup:
    subscribe:
      message:
        payload:
          type: object
          properties:
            displayName:
              type: string
            email:
              type: string
              format: email

```

login.yaml
```
asyncapi: '2.2.0'
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signup

channels:
  user/loggenin:
    subscribe:
      message:
        payload:
          type: object
          properties:
            displayName:
              type: string

```
Bundled (terminal) output
```
  asyncapi: '2.2.0',
  info: {
    title: 'Account Service',
    version: '1.0.0',
    description: 'This service is in charge of processing user signup'
  },
  channels: {
    'user/signedup': { subscribe: [Object] },
    'user/loggenin': { subscribe: [Object] }
  }
```

Expected output
```
asyncapi: '2.2.0'
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge for processing user authentication 

channles:
  user/signedup:
    subscribe:
      message:
        payload:
          type: object
          properties:
            displayName:
              type: string
            email:
              type: string
              format: email
  user/loggedin:
    subscribe:
      message:
        payload:
          type: object
          properties:
            displayName:
              type: string
```

**Comment by Souvikns** [comment]
Would be better if you open a WIP PR then I can take a look at your changes, but this is happening most probably because you are using `document.json()` that's why you are getting output in `JSON` format for `YAML` format you have to use `document.yml()`  you can refer this document to learn more https://github.com/asyncapi/bundler/blob/master/API.md#Document+yml

**Comment by amanbedi1** [comment]
@Souvikns thanks its working.

**Comment by amanbedi1** [comment]
hey @Souvikns @derberg  I just made a <a href ="https://github.com/asyncapi/cli/pull/260">PR</a>. Please review it

**Comment by s1mrankaur** [comment]
@amanbedi1   @Souvikns 
My yml file has

`      $ref: ./components/channels/site-channels.yml#/channels/sites-change
`

The bundle command errors out with 
    `ENOENT: no such file or directory,`

as it doesn't get the path right.

My structure is 
```

vlncc-event-catalog2/
  event-specs/
     channels/
       site-channels.yml
     asyncpi.yml


```

and the command was looking for
C:\\BLBLA\vlncc-event-catalog2\components\channels\site-channels.yml'

i.e skipped event-specs folder somehow.
