### ISSUE TITLE
Add all-contributors section in readme

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/cli#226]
#### Reason/Context
In order to highlight all the amazing people who make this library possible, we to add the all-contributors section as we have in all of the other repositories.

Follow https://allcontributors.org/docs/en/cli/usage#all-contributors-init to initialize and add contributors.

Similar PR was done in the website repo: https://github.com/asyncapi/website/pull/460

**Comment by jonaslagoni** [comment]
I think this makes a good first issue, can anyone assign it the label?

**Comment by magicmatatjahu** [comment]
@jonaslagoni as I see Łukasz will add it https://github.com/asyncapi/cli/pull/223 😆

**Comment by jonaslagoni** [comment]
Ah 😆 Perfect 👌

**Comment by imabp** [comment]
I guess we can close this issue @jonaslagoni  😄, you can see the latest changes :)
