### ISSUE TITLE
feat: integration-service and integration-config-template for AsyncAPI CLI

### ISSUE THREAD

**Issue by imabp** [asyncapi/cli#233]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
Currently, every command has to be separately integrated, like diff, validate, so to avoid this manually adding things everytime, why not design an `integration-configuration-template` and `integrationService` which will be used to add more integrations to cli, and probably less work we have to do.. 
 
- How will this change help?
Devleoper Experience

- What is the motivation? 
CLI itself.

**FLOW**
 
`asyncapi integrate add --config="./integrationName.config.json"`
This will create an integration service, up and running, folks can use the integration commands using 

`asyncapi integratationName  commandName`

To delete an integration
`asyncapi integrate delete integrationName`

To list out all integrations
`asyncapi integrate list`

With addition to this, we bring in cli with default integrationConfigs, like validate, new, diff, in an `integrations/_default/` directory, which will be used for default integrations, to make sure, CLI is usable in first use.  

A great benefit will be, this will make CLI highly customizable, and  folks can build more integrations on top of it. 

**Need some inputs and views from the community, how you feel about this idea, we can brainstorm on this, soon after V1 release? And definitely like to work on it**

**Comment by magicmatatjahu** [comment]
I don't understand one thing, is this integration to be done in cli itself or on the library side? If on the cli side why call it an integration and not a command? 

Similar idea: https://github.com/asyncapi/community/issues/249

**Comment by imabp** [comment]
Yeah, thats the crux, we need to build the integration-config inside the respective libraries, and the format of integration-config will be decided by cli.

**Comment by magicmatatjahu** [comment]
Thanks! So I think that we should go with https://github.com/asyncapi/community/issues/249 direction. We don't only have CLI but also Studio and ServerAPI to make integration. Also I'm not fan to create such a command, because it's a copy paste of simple file. We should rather focus on discussing how to do this generically, not just looking at the CLI but at the overall problem of integration in other tools
