### ISSUE TITLE
handling unhandledRejection for support of nodejs version < `15.x.x`

### ISSUE THREAD

**Issue by imabp** [asyncapi/cli#234]
With introduction to NodeJS 15 blog
https://developer.ibm.com/blogs/nodejs-15-release-blog/

All unhandled rejections will be treated as strictly as errors , instead of warnings. Hence the process will be closed.

This is directly affecting our cli watcher for nodejs < 15 and nodejs > 15, as mentioned here https://github.com/asyncapi/cli/pull/220#issuecomment-1044498676

@magicmatatjahu has suggested the following solution  to this 
>```ts
> process.on('unhandledRejection', (reason, promise) => {
>  // throw error and stop process
> });```

This issue tries to address the above problem

**Comment by magicmatatjahu** [comment]
>=15 versions handle that in proper way, <15 only have a problem.

**Comment by imabp** [comment]
Oops @ritik307 , I can update you on this...
I am working on it, post the watcher PR #220   ...as this issue has a dependency on it 
 
But if needed help, I would definitely update here. 😊

**Comment by ritik307** [comment]
> Oops @ritik307 , I can update you on this...
> I am working on it, post the watcher PR #220   ...as this issue has a dependency on it 
>  
> But if needed help, I would definitely update here. 😊

Sure no problem 😊

**Comment by imabp** [comment]
@magicmatatjahu ,just curious, how do we start working on this now. 
You have any design suggestions?

**Comment by imabp** [comment]
This is already solved ..mr bot 🤭
