### ISSUE TITLE
Have pipeline to create assets for different operating systems 

### ISSUE THREAD

**Issue by Souvikns** [asyncapi/cli#235]
Right now the only way to install `@asyncapi/cli` is through npm and it also depends on nodejs. Would be nice to have a pipeline that would generate different standalone tarballs according to the most popular operating systems.

#### Description
1. [Oclif](https://oclif.io/) helps us create installers for mac,windows and linux. [read here](https://oclif.io/docs/releasing).
2. All we need is to create an action that creates different installers and uploads them as a release asset. 

With this task you will learn:

- how AsyncAPI uses gh actions to create releases. Check out [this video](https://www.youtube.com/watch?v=IRxKwzLuohM&t=917s) from @derberg where he explains our global workflow structure and how we create releases. 
- you will write GitHub actions 
- you will learn about CLI and [oclif](https://oclif.io/)

**Comment by imabp** [comment]
Definitely want to work on this.

**Comment by derberg** [comment]
@imabp I have it in progress already -> https://github.com/asyncapi/cli/pull/187

**Comment by imabp** [comment]
Awesome!! 🥳
