### ISSUE TITLE
Update README with new logo banner

### ISSUE THREAD

**Issue by mcturco** [asyncapi/cli#257]
#### Reason/Context
This is to replace the old AsyncAPI logo in this repo's README with the banner attached below that represents the new branding.

**Here are a few guidelines for this change as well:**
1. Make sure you are using [Markdown syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) only
2. Be sure to remove the old logo as well as the old title of the repo as this image will replace both elements
3. Make sure you link this image to the website: `https://www.asyncapi.com`
4. If there is any description text below the repo title, let's make it left-aligned if it isn't already, so as to match the left-alignment of the content in the new banner image

**Download the image file:**
[github-repobanner-cli.png.zip](https://github.com/asyncapi/cli/files/8232755/github-repobanner-cli.png.zip)

------

#### Banner preview
_Please note that this is only a preview of the image, the contributor should download and use the above zip file_ 

<img width="830" alt="github-repobanner-cli" src="https://user-images.githubusercontent.com/60163079/157887351-e61de58d-b1eb-4fd2-8ba1-8601877c494a.png">

**Comment by amanbedi1** [comment]
I would like to work on this issue. Just a clarification as the current logo is serving from another repository so should I put this new logo in assets folder of this repository.

**Comment by derberg** [comment]
yeah, `assets` is pretty standard I think that we have already in other repos. Go ahead 🚀

**Comment by amanbedi1** [comment]
Here is my <a href="https://github.com/asyncapi/cli/pull/258">PR</a> please review it.

**Comment by boyney123** [comment]
Guess we can close this one now @mcturco?

**Comment by mcturco** [comment]
Yes, all set. Thanks @boyney123
