### ISSUE TITLE
validate command returns 0 exit code when validation error occurs

### ISSUE THREAD

**Issue by andrewshawcare** [asyncapi/cli#285]
#### Describe the bug
It was expected that when a validation error occurs when running the validate command, a non-zero exit code would be used. Instead, it returns 0.

#### How to Reproduce
```
> touch asyncapi.yml ; npx @asyncapi/cli validate asyncapi.yml ; echo $? ; rm asyncapi.yml
ValidationError: Document can't be null or falsey.
0
```

#### Expected behavior
A non-zero error code would be used.

**Comment by peter-rr** [comment]
@fmvilas Sure! This command is already familiar to me, so let's go for it 💪

**Comment by TamimiGitHub** [comment]
Hey @peter-rr  ! Not sure if you got the chance to get around this :)
