### ISSUE TITLE
Help validate Windows installer publishing

### ISSUE THREAD

**Issue by derberg** [asyncapi/cli#302]
#### Reason/Context

[This](https://github.com/asyncapi/cli/pull/187) PR introduced automation for publishing of MacOS `pkg` file. It was also designed in the way that it should be easy to plug in generation of installer files for Windows and Linux.

**This issue is for folks that work on Windows machine** and can do some local testing to check if all works as expected

#### Description

* First make sure installer generation works:
  * run `npm run pack:windows`
  * installer should be produced in `dist` directory. Try to install CLI using it
* Then open a PR with the following changes
  * Uncomment this part in the artifact publishing job: https://github.com/asyncapi/cli/blob/master/.github/workflows/upload-release-assets.yml#L22-L25 and modify as much as needed
  * I don't know what will be the name of the generated installer, so you will probably have to refactor existing script for MacOS installer renaming -> https://github.com/asyncapi/cli/blob/master/scripts/macosPackRename.js
  * Update Readme instructions on how to quickly install CLI with new installer -> https://github.com/asyncapi/cli#installation

**Comment by Souvikns** [comment]
@derberg for windows should we have a `.msi` installer or use some package manager like `chocolatey`?

**Comment by derberg** [comment]
@Souvikns for chocolatey we have this issue https://github.com/asyncapi/cli/issues/304 as work is different than the one described here, and definitely not easy good first issue. 

and yes, afaik, https://github.com/oclif/oclif#oclif-pack-win produces `.msi` but only Windows user can confirm.

I think we need both. Just like with my initial work on MacOS, I worked on `brew` and also `pkg` for those that do not use `brew`

**Comment by Souvikns** [comment]
I tested it and it works, we just need to install `p7zip` and `nsis` to run the `pack:windows` command.

**Comment by Souvikns** [comment]
I will just wait for https://github.com/asyncapi/cli/pull/325 and then open a PR for this

**Comment by Souvikns** [comment]
@derberg I am getting this error while running `npm run pack:win` I am unable to find shasum for windows. 

![image](https://user-images.githubusercontent.com/41781438/200851477-4318b2a2-3166-45e0-a1c7-ed050983033f.png)

**Comment by derberg** [comment]
@Souvikns hey man, since we use latest oclif, maybe you could give it another try?

**Comment by Souvikns** [comment]
Will do 👍🏼

**Comment by Souvikns** [comment]
@derberg now everything runs, and we get two `.exe` files, and it looks like it is the installer.

![image](https://user-images.githubusercontent.com/41781438/233114174-148dc3d6-0f93-4502-8c5e-275144fc9fd9.png)
