### ISSUE TITLE
Help validate Linux installer publishing

### ISSUE THREAD

**Issue by derberg** [asyncapi/cli#303]
#### Reason/Context

[This](https://github.com/asyncapi/cli/pull/187) PR introduced automation for publishing of MacOS `pkg` file. It was also designed in the way that it should be easy to plug in generation of installer files for Windows and Linux.

**This issue is for folks that work on Linux machine** and can do some local testing to check if all works as expected

#### Description

* First make sure installer generation works:
  * run `npm run pack:linux`
  * installer should be produced in `dist` directory. Try to install CLI using it
* Then open a PR with the following changes
  * Uncomment this part in the artifact publishing job: https://github.com/asyncapi/cli/blob/master/.github/workflows/upload-release-assets.yml#L18-L21 and modify as much as needed
  * I don't know what will be the name of the generated installer, so you will probably have to refactor existing script for MacOS installer renaming -> https://github.com/asyncapi/cli/blob/master/scripts/macosPackRename.js
  * Update Readme instructions on how to quickly install CLI with new installer -> https://github.com/asyncapi/cli#installation

**Comment by aayushmau5** [comment]
Hey! I use linux. I'll try this out.

**Comment by aayushmau5** [comment]
![image](https://user-images.githubusercontent.com/54525741/176934948-e0a83e21-6b3a-4184-99c5-811713a1803c.png)
Got this error.

**Comment by derberg** [comment]
@aayushmau5 thanks a bunch for looking into this 🙏🏼 

yeah `.deb` is just there in a comment but doesn't have to end up like this. I do not even know what they generate really. IT can be tarball if this is ok, as long as there are good instructions on how to use it on linux

in regards to the error - seem to me like some local permissions issue no?

**Comment by aayushmau5** [comment]
> in regards to the error - seem to me like some local permissions issue no?

Maybe. I'll look into this, and let you know whether it's an error on my end or not.

**Comment by derberg** [comment]
@aayushmau5 hey, any luck?

**Comment by aayushmau5** [comment]
@derberg Ok, I was able to get the package. Had to install some additional packages related to apt package manager.

The `pack:linux` command outputs the following file:
![image](https://user-images.githubusercontent.com/54525741/180138051-0d5820d1-029e-4347-93e0-e7a6f816cf20.png)

Ran `dpkg -i asyncapi_0.21.2.515e58d-1_amd64.deb` to install the deb file. And, we got `asyncapi` command now :D

**Comment by derberg** [comment]
yes yes yes 🚀 
 
THANKS!!!

you ok to take it forward and extend release pipeline as I described in the PR? Existing "renaming" script will for sure have to be extended with rename of the `.deb` file.

**Comment by aayushmau5** [comment]
> you ok to take it forward and extend release pipeline as I described in the PR? 

Sure. :rocket:
