### ISSUE TITLE
Incorrect context help message - [asyncapi config context]

### ISSUE THREAD

**Issue by lennonkh** [asyncapi/cli#315]
While adding new context for AsyncAPI CLI there is an incorrect help message about further actions. It suggests calling an incorrect message

#### How to Reproduce
asyncapi config context add [context-name] [context-path]
<img width="868" alt="async_context" src="https://user-images.githubusercontent.com/15107731/177261323-56638a73-cf88-4ba4-be2e-bac72e2a6f1d.png">

#### Expected behavior
https://github.com/asyncapi/cli/blob/master/src/commands/config/context/add.ts should state 
`You can set it as your current context: asyncapi **config** context use ${contextName}`

**Comment by lennonkh** [comment]
I can fix the issue. Please assign it to me.

**Comment by Souvikns** [comment]
@lennonkh thanks for the issue, we already have a PR for this, https://github.com/asyncapi/cli/pull/294 it will be merged soon

**Comment by lennonkh** [comment]
Looks like it's an additional place - https://github.com/asyncapi/cli/blob/master/src/commands/config/context/add.ts, I don't see the fix in PR provided.
