### ISSUE TITLE
Create `create-template` in AsyncAPI organization 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/cli#337]
#### Reason/Context
Stumbled upon this and thought it would be perfect for the generator. We could offer a way to use the [init function](https://docs.npmjs.com/cli/v7/commands/npm-init) which will allow people to more quickly setup new templates.

By creating `create-template` in the AsyncAPI scope we can do the following example commands:
- `npm init @asyncapi/template --react`
- `npm init @asyncapi/template --nunjucks`
- `npm init @asyncapi/template`

#### Description
This will significantly speed up the process of creating new ones and make it more accessible for people. This is similar to what React have - https://github.com/facebook/create-react-app

**Comment by derberg** [comment]
I think we should follow the same direction that will be done with https://github.com/asyncapi/cli/pull/418

**Comment by Shurtu-gal** [comment]
@derberg @jonaslagoni can I work on this?

**Comment by derberg** [comment]
yeah, but problem is not the implementation, we need a clear definition of the project that we would like to have generated with this new command. Some brainstorming session is kinda needed

**Comment by Shurtu-gal** [comment]
Still Relevant 🤝

**Comment by Shurtu-gal** [comment]
Still relevant 🤝

**Comment by AayushSaini101** [comment]
I want to work on this. :)

**Comment by DhairyaMajmudar** [comment]
Hi @derberg @jonaslagoni I would love to work on this issue, actually I am developing a similar kind of npm package https://github.com/DhairyaMajmudar/majirya-cli

This package a CLI Tool which simplifies mern stack and T3 stack web development.

**Comment by Amzani** [comment]
Hi @DhairyaMajmudar @AayushSaini101 was the first to express his interest in working on this issue.
Feel free to pick the other issues in the project.

Thanks

**Comment by DhairyaMajmudar** [comment]
Sure looking forward to apply for an another issue, thank you : )

**Comment by AayushSaini101** [comment]
We can implement a command that is asyncapi init that will generate a template for the user, and we have already have template of template structure https://github.com/asyncapi/template-for-generator-templates we can simply use it @Amzani @Souvikns

**Comment by aeworxet** [comment]
### Bounty Issue's service comment

Text labels: `bounty/2024-Q3`, `bounty/advanced`, `bounty/coding`
First assignment to third-party contributors: [2024-06-21 00:00:00 UTC+12:00](https://time.lol/#2024-06-21T00:00:00+12:00)
End Of Life after: [2024-07-31 23:59:59 UTC-12:00](https://time.lol/#2024-07-31T23:59:59-12:00)

@asyncapi/bounty_team

##### The Bounty Program is not a Mentorship Program. The accepted level of Bounty Program Participants is **Middle**/**Senior**.
##### Third-party contributors should [coherently articulate](https://github.com/asyncapi/converter-js/issues/233#issuecomment-2119226365) how they are going to approach the resolution process when expressing a desire to work on this Bounty Issue.

**Comment by AayushSaini101** [comment]
The current command to generate the glee project is asyncapi new glee --name <name>, and we need to generate only for react engine template because it is more efficient. In that case, we can introduce the new command that is :
asyncapi new template --name <name>. 
and the structure of the template will be:
asyncapitemplate
  -->template
 ------>index.js 
  --->package.json
 Reference template format for react engine: https://www.asyncapi.com/docs/tools/generator/template-development.

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Advanced        |2024-06-18                 |[2024-07-01](https://time.lol/#2024-07-01T00:00:00+12:00)              |**[2024-08-25](https://time.lol/#2024-08-25T23:59:59-12:00)**        |[2024-07-21](https://time.lol/#2024-07-21T23:59:59-12:00)         |[2024-08-11](https://time.lol/#2024-08-11T23:59:59-12:00)         |**[2024-08-25](https://time.lol/#2024-08-25T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR218) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR105).

**Comment by aeworxet** [comment]
@Amzani
Please confirm the technical resolution of this Bounty Issue or delegate this action to other Maintainers.

**Comment by aeworxet** [comment]
Since @Amzani is vacationing
![image](https://github.com/user-attachments/assets/10f0e884-d047-47c7-9307-50b2db4f8198)

@Souvikns, @Shurtu-gal, can one of you please confirm the technical resolution of this Bounty Issue?

**Comment by Souvikns** [comment]
@aeworxet @AayushSaini101 has resolved this issue by merging #1476.

**Comment by aeworxet** [comment]
### Bounty Issue Is Completed 🎉

@AayushSaini101, please go to the [AsyncAPI page on Open Collective](https://opencollective.com/asyncapi) and submit an invoice for `USD 400.00` with the expense title `Bounty cli#337`, tag `bounty`, and full URL of this Bounty Issue in the description.
