### ISSUE TITLE
Adding an activity loader

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/cli#394]
I believed the generator should have an activity loader that indicates the generator is running

I was running the generator on my windows machine, but for some reason it took time and I couldn't tell if it was actually generating or not.

**Comment by Souvikns** [comment]
@AceTheCreator we did implement an activity loader for the generator command. 


https://github.com/asyncapi/cli/blob/087810293d07d8acae4954a208574c2f336e3a27/src/commands/generate/fromTemplate.ts#L187

![Image](https://user-images.githubusercontent.com/41781438/211277043-31d0da60-8563-4068-8a94-e3e2439ba59a.png)

**Comment by derberg** [comment]
still needed

**Comment by sambhavgupta0705** [comment]
would like to know what improvement is needed.
just a little confused that @Souvikns mentioned that we have implemented an activity loader but still it is needed

**Comment by derberg** [comment]
@AceTheCreator can you have a look?

**Comment by derberg** [comment]
closing, no response
