### ISSUE TITLE
Add Kotlin support for model generation

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/cli#432]
#### Reason/Context
As of Modelina version `1.0.0-next.41` Kotlin is supported as a generator, which the CLI also need to support.

To solve this issue you must do the following:

1. Update Modelina to the new version.
2. Add Kotlin to the list of supported languages: https://github.com/asyncapi/cli/blob/c2cf56d5bfbc8ab424ad89dfc2eb31b042cbca35/src/commands/generate/models.ts#L6
3. Add kotlin to the list of languages that needs `packageName` argument: https://github.com/asyncapi/cli/blob/c2cf56d5bfbc8ab424ad89dfc2eb31b042cbca35/src/commands/generate/models.ts#L67
4. Import the `KotlinFileGenerator`: https://github.com/asyncapi/cli/blob/c2cf56d5bfbc8ab424ad89dfc2eb31b042cbca35/src/commands/generate/models.ts#L1
5. Add the following to [the switch case](https://github.com/asyncapi/cli/blob/c2cf56d5bfbc8ab424ad89dfc2eb31b042cbca35/src/commands/generate/models.ts#L102):
```ts
    case Languages.kotlin:
      if (packageName === undefined) {
        throw new Error('In order to generate models to Kotlin, we need to know which package they are under. Add `--packageName=PACKAGENAME` to set the desired package name.');
      }
      fileGenerator = new KotlinFileGenerator();
      fileOptions = {
        packageName
      };
```
6. Add the [following tests for Kotlin](https://github.com/asyncapi/cli/blob/master/test/commands/generate/models.test.ts#L141):
```ts
  describe('for Kotlin', () => {  
    test
      .stderr()
      .stdout()
      .command([...generalOptions, 'kotlin', './test/specification.yml', `-o=${ path.resolve(outputDir, './kotlin')}`, '--packageName', 'test.package'])
      .it('works when file path is passed', (ctx, done) => {
        expect(ctx.stderr).toEqual('');
        expect(ctx.stdout).toContain(
          'Successfully generated the following models: '
        );
        done();
      });
    test
      .stderr()
      .stdout()
      .command([...generalOptions, 'kotlin', './test/specification.yml', `-o=${ path.resolve(outputDir, './kotlin')}`])
      .it('fails when no package defined', (ctx, done) => {
        expect(ctx.stderr).toEqual('Error: In order to generate models to Kotlin, we need to know which package they are under. Add `--packageName=PACKAGENAME` to set the desired package name.\n');
        expect(ctx.stdout).toEqual('');
        done();
      });
  });
```
7. Add the Kotlin command to the main readme: https://github.com/asyncapi/cli/blob/master/README.md#usage

That is all that is needed to support Kotlin in the CLI.

**Comment by jonaslagoni** [comment]
Can someone add `good-first-issue` label? 🙂

**Comment by sambhavgupta0705** [comment]
HI, I would like to work on this issue.
