### ISSUE TITLE
Integrate CLI docs with asyncapi website

### ISSUE THREAD

**Issue by derberg** [asyncapi/cli#448]
#### Reason/Context

AsyncAPI tools should also have documentation available in asyncapi.com/docs

We have AsyncAPI Generator docs there already -> asyncapi.com/docs/tools/generator

#### Description

We need here, in `cli` repo the same workflow that we already have in AsyncAPI Generator -> https://github.com/asyncapi/generator/blob/master/.github/workflows/update-docs-in-website.yml

But of course not copied 1:1, certain renaming must be done.

Author of related automation is @Florence-Njeri in case you have some question

**Comment by activus-d** [comment]
@derberg I will work on this issue.

**Comment by derberg** [comment]
@activus-d lemme know if I can somehow help

**Comment by activus-d** [comment]
@derberg Sorry that I have not started working on this task. I was busy with my [Outreachy](https://outreachy.org/) internship. I will start working on it next week.

**Comment by derberg** [comment]
no worries, good luck with Outreachy!

**Comment by derberg** [comment]
this is done already
