### ISSUE TITLE
Cannot create new file based on example 

### ISSUE THREAD

**Issue by tsauerwein** [asyncapi/cli#453]
#### Describe the bug
When using `asyncapi new` to create a new file based on an example, a `TypeError` is raised.

#### How to Reproduce
```
$ asyncapi new
? name of the file? test.yml
? would you like to start your new file from one of our examples? Yes
TypeError: Cannot read properties of null (reading 'type')
```

Versions:
```
$ asyncapi --version
@asyncapi/cli/0.31.0 darwin-arm64 node-v18.14.0
$ node --version
v18.14.0
```
#### Expected behavior
No error is raised.

**Comment by derberg** [comment]
I tried to reproduce the issue, but it works every single time. Can you try to use latest CLI and confirm?

**Comment by tsauerwein** [comment]
Thanks for checking! I can confirm that I no longer have the issue with version 0.31.1.
