### ISSUE TITLE
Diagnostics view in editor is showing different validation issues than "asyncapi validate"

### ISSUE THREAD

**Issue by tsauerwein** [asyncapi/cli#456]
#### Describe the bug
The validation issues shown in the Diagnostics view of the editor are different to the ones you see when running `asyncapi validate`. 

#### How to Reproduce
Open the provided MQTT example in the editor and also run `asyncapi validate` on it. Some issues are shown both in the editor and also on the console. But for example `asyncapi2-message-messageId` is only shown in the console, or `Operation "description" must be present and non-empty string.` is only shown in the editor.

![Screenshot 2023-02-13 at 11 29 11](https://user-images.githubusercontent.com/266474/218434936-ee427881-0582-4d68-ba41-66d6b5e715a9.png)

#### Expected behavior
I would expect that the same issues are shown both in the editor and on the console.

**Comment by magicmatatjahu** [comment]
@tsauerwein try to use the latest cli (probably your version of cli has old Studio version <0.17.1).

**Comment by tsauerwein** [comment]
Thanks, for the fast response! It's looking better now.

There is still a small difference: When using references, an issue is shown twice in the editor (where the reference is used and also where it's defined), while there is only one issue on the console. But you could see that as a feature instead of a bug.

![Screenshot 2023-02-13 at 13 05 53](https://user-images.githubusercontent.com/266474/218453430-21e354da-a485-4d27-8b86-f782e42bc1c7.png)

**Comment by magicmatatjahu** [comment]
@tsauerwein Ahh, yes! Studio uses the `next-major.14` version of ParserJS (which performs validation) but CLI uses `.15` version, where we filter some duplicated errors. Thanks for info!
