### ISSUE TITLE
Generate marshalling functions for TypeScript models

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/cli#460]
#### Reason/Context
In Modelina for TypeScript, you can make it generate the models with marshaling functions and it should also be possible through the CLI.

To do this I suggest we add a flag called `tsMarshalling` as a boolean. If true the generator should include the following options:
```
  presets: [
    {
      preset: TS_COMMON_PRESET,
      options: {
        marshalling: true
      }
    }
  ]
```
Which should be added here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/src/commands/generate/models.ts#L118 as the code example show: https://github.com/asyncapi/modelina/blob/master/examples/typescript-generate-marshalling/index.ts

These will be the generated results: https://github.com/asyncapi/modelina/blob/master/examples/typescript-generate-marshalling/__snapshots__/index.spec.ts.snap

Remember to also add a test here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/test/commands/generate/models.test.ts#L39

Feel free to reach out if you have any questions or get stuck!

**Comment by jonaslagoni** [comment]
@AayushSaini101 there are no assignments or anything in that way, so it's all about just doing it 😊 Go for it 👍

**Comment by NileshPant1999** [comment]
@AayushSaini101 if you are not doing this i will be adding this change will create a pr shortly

**Comment by NileshPant1999** [comment]
this is being discussed here
https://github.com/asyncapi/cli
