### ISSUE TITLE
Generate example function for TypeScript models

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/cli#462]
#### Reason/Context
In Modelina for TypeScript, you can make it generate the models generate functions that return a basic instance example, this should be possible through the CLI.

To do this I suggest we add a flag called `tsExampleInstance` as a boolean. If true the generator should include the following options:
```
  presets: [
    {
      preset: TS_COMMON_PRESET,
      options: {
        example: true
      }
    }
  ]
```
Which should be added here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/src/commands/generate/models.ts#L118 as the code example shows: https://github.com/asyncapi/modelina/blob/master/examples/typescript-generate-jsonbinpack/index.ts

These will be the generated results: https://github.com/asyncapi/modelina/blob/master/examples/typescript-generate-example/__snapshots__/index.spec.ts.snap

Remember to also add a test here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/test/commands/generate/models.test.ts#L39

Related documentation: https://github.com/asyncapi/modelina/blob/master/docs/languages/TypeScript.md#generate-example-data-function

Feel free to reach out if you have any questions or get stuck!

**Comment by bhavyastar** [comment]
Hey @jonaslagoni @Souvikns I would like to work on this issue!

**Comment by chinma-yyy** [comment]
Hey @jonaslagoni  , I was working on this issue and I have almost completed it but when I added the test script for the functionality it gives an error 
![image](https://github.com/asyncapi/cli/assets/112387862/679122de-8313-4919-ab4a-375417b56db3)
for every `toEqual` it is giving this error what should I do? Earlier it used to work fine.

**Comment by jonaslagoni** [comment]
Try add the PR as a draft PR so we can see the changes @chinma-yyy 🙂
