### ISSUE TITLE
Generate overwritten GetHashCode method for C# models

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/cli#467]
#### Reason/Context
In Modelina for C#, you can make it generate the models with the GetHashCode method overwritten, this should be possible through the CLI.

To do this I suggest we add a flag called `csharpHashcode` as a boolean. If true the generator should include the following options:
```  
presets: [
    {
      preset: CSHARP_COMMON_PRESET,
      options: {
        hashCode: true
      }
    }
  ]
```
Which should be added here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/src/commands/generate/models.ts#L137 as the code example shows: https://github.com/asyncapi/modelina/blob/master/examples/csharp-generate-equals-and-hashcode/index.ts

These will be the generated results: https://github.com/asyncapi/modelina/blob/master/examples/csharp-generate-json-serializer/__snapshots__/index.spec.ts.snap

Remember to also add a test here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/test/commands/generate/models.test.ts#L95

Related documentation: https://github.com/asyncapi/modelina/blob/master/docs/languages/Csharp.md#generate-models-with-equals-and-gethashcode-methods

Feel free to reach out if you have any questions or get stuck!

Related issue https://github.com/asyncapi/cli/issues/466

**Comment by octonawish-akcodes** [comment]
Can I take this

**Comment by jonaslagoni** [comment]
@octonawish-akcodes there are no assignments or anything in that way, so it's all about just doing it 😊 Go for it 👍

**Comment by kaushik-rishi** [comment]
Working on it @jonaslagoni

**Comment by kaushik-rishi** [comment]
Hey @jonaslagoni. 
Why does it seem like modelina's generating the same code when providing presets of hashcode, equals either of these or both of these.
- when i have my preset set to `equals: true`, my hashcode method is being overriden
- when i have my preset set to `hashcode: true`, my equals method is being overriden

or is this a default behaviour ? (kinda new to c#)

[reference gist of the outputs generated](https://gist.github.com/kaushik-rishi/74d52096a6e1d224ca827827201ed923)

**Comment by kaushik-rishi** [comment]
@jonaslagoni 

We can include both the `equals` and `hashcode` flags in a single preset.
What are we supposed to do if the user provides both the `autoImplement` flag and the `hashcode` flag ? - Are we allowed to have both the presets ?

May be i'm lacking some knowledge of C# here meaning to what these flags actually are doing to the generated models.

**Comment by jonaslagoni** [comment]
By default (for this preset), there is no difference between not setting the options and setting them to true, both are added by default.

This means that in order to turn a specific rendering off, you have to set the option to `false` 🙂 

For autoImplement, its actually a bit obscure and the example does not really show it correct... Because the preset, is just the default preset, with custom options (i.e. it's actually rendered twice, we just don't know it). 

>What are we supposed to do if the user provides both the autoImplement flag and the hashcode flag ? - Are we allowed to have both the presets ?

Yep, you can have as many as you wish, you can read more about them here: https://github.com/asyncapi/modelina/blob/master/docs/presets.md

So as long as the CSHARP_DEFAULT_PRESET is first, you can stack them similar to something like this (just pseudo code):
```
let options = {presets: [], collectionType: csharpArrayType as 'Array' | 'List'};
if(csharpAutoImplement) {
  options.presets.push({
            preset: CSHARP_DEFAULT_PRESET,
            options: {
              autoImplementedProperties: true
            }
          })
}
if(equals || hashcode) {
  options.presets.push(
    {
      preset: CSHARP_COMMON_PRESET,
      options: {
        equal: equals,
        hashCode: hashcode
      }
    })
}
fileGenerator = new CSharpFileGenerator(options);
```

**Comment by kaushik-rishi** [comment]
@jonaslagoni thanks. Cleared my mind.

Do you think one PR would be sufficient to fix both the issues in that case?

**Comment by jonaslagoni** [comment]
Definitely 👍
