### ISSUE TITLE
Generate auto-implemented properties for C# models

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/cli#468]
#### Reason/Context
In Modelina for C#, you can make it generate the models with auto-implemented properties, this should be possible through the CLI.

To do this I suggest we add a flag called `csharpAutoImplement` as a boolean. If true the generator should include the following options:
```  
  presets: [
    {
      preset: CSHARP_DEFAULT_PRESET,
      options: {
        autoImplementedProperties: true
      }
    }
  ]
```
Which should be added here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/src/commands/generate/models.ts#L137 as the code example shows: https://github.com/asyncapi/modelina/blob/master/examples/csharp-auto-implemented-properties/index.ts

These will be the generated results: https://github.com/asyncapi/modelina/blob/master/examples/csharp-auto-implemented-properties/__snapshots__/index.spec.ts.snap

Remember to also add a test here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/test/commands/generate/models.test.ts#L95

Related documentation: https://github.com/asyncapi/modelina/blob/master/docs/languages/Csharp.md#generate-models-with-auto-implemented-properties

Feel free to reach out if you have any questions or get stuck!

**Comment by octonawish-akcodes** [comment]
Can I work on this one

**Comment by jonaslagoni** [comment]
@octonawish-akcodes there are no assignments or anything in that way, so it's all about just doing it 😊 Go for it 👍

**Comment by prayutsu** [comment]
@jonaslagoni can I take this as well?

**Comment by jonaslagoni** [comment]
No need to ask @prayutsu, as long as there are no recent updates from people, it's all yours 🔥
