### ISSUE TITLE
Add support for 2.6.0 AsyncAPI specs

### ISSUE THREAD

**Issue by zigad** [asyncapi/cli#494]
#### Describe the bug
If I try to run the command `asyncapi validate asyncapi.yaml` on a 2.6.0 AsyncAPI specification i get an error: `ValidationError: Version 2.6.0 is not supported.`

I tested on latest 0.34.0 version and this is still an issue.

#### How to Reproduce
Generate 2.6.0 AsyncAPI sepcification, run it with `asyncapi validate asyncapi.yaml `.

Example YAML file with 2.6.0 version: 
[asyncapi.txt](https://github.com/asyncapi/cli/files/11111704/asyncapi.txt) (rename from .txt to .yaml)

![Screenshot 2023-03-30 at 14 45 26](https://user-images.githubusercontent.com/41201503/228840127-35640e2d-36c7-48d1-95c4-dac1dae06d02.png)

#### Expected behavior
Expected behaviour would be that the command would validate the file and return any errors/mistakes.

**Comment by derberg** [comment]
@smoya Parser's 2 RC uses `@asyncapi/specs` that should support `2.6`. Is there something more that should be done in the RC to support new available version?

**Comment by zigad** [comment]
I managed to fix this issue. 0.34.0 does indeed support asyncapi 2.6. I had a different problem. I was running this command on a pre-commit hook and somehow it grabbed an old version of asyncapi cli. I managed to fix this by running `./node_modules/.bin/asyncapi validate $file` command instead of `asyncapi validate $file`
