### ISSUE TITLE
Do something with automated brew formula update

### ISSUE THREAD

**Issue by derberg** [asyncapi/cli#503]
### Context

whenever we release here, bot also creates PR to brew to update formula -> https://github.com/asyncapi/cli/blob/master/.github/workflows/bump-homebrew-formula.yml

because sometimes we have days when we merge a lot of PRs, we become harmful and spammers to `brew` folks -> https://github.com/Homebrew/homebrew-core/pull/127077

### Solution

I was thinking that maybe we should just change from `push` event to `cron` and it will be ok if we run update of brew formula:
- once a day, end of the day
- and PR is opened on `brew` when there are changes, of course not every day

### IMPORTANT

Before we fix this problem, @Souvikns @magicmatatjahu @boyney123 let us make sure we do not merge more than one `feat` or `fix` a day 🙏🏼 

Thoughts ?

**Comment by derberg** [comment]
@achiverram28 definitely, but please give other maintainers few days to share opinion. If there is silent approval or not-silent YES for the cron approach, you can definitely submit PR to update the GitHub worflow

**Comment by derberg** [comment]
@achiverram28 go ahead and update the workflow to make sure it still works but on `cron` event trigger.

**Comment by achiverram28** [comment]
Yup , on it
