### ISSUE TITLE
Attempting to generate Rust models produces an inscrutable error message

### ISSUE THREAD

**Issue by coriolinus** [asyncapi/cli#549]
#### Describe the bug

Attempting to generate Rust models produces an inscrutable error message.

#### How to Reproduce

Version: `@asyncapi/cli/0.40.4 wsl-x64 node-v16.15.1`

```sh
$ asyncapi generate models rust openapi/render_service/v1/render_service.openapi.yaml
Error: EEXIT: 1
```
#### Expected behavior

Either successful generation of models in Rust, or some kind of human-readable explanation of what went wrong.

**Comment by kaushik-rishi** [comment]
@coriolinus can you share the file for which you are trying to generate the models ?

**Comment by coriolinus** [comment]
That file is still closed-source for now, unfortunately.

**Comment by kaushik-rishi** [comment]
@coriolinus oh no problem!
can you try the same command with the file mentioned in the asyncapi docs.
[this one](https://gist.github.com/kaushik-rishi/f9e7ae0f0e49666995ac37607309e56d)

**Comment by coriolinus** [comment]
That does appear to work: 

```bash
$ asyncapi generate models rust asyncapi.yaml
Thu 25 May 2023 09:08:03 AM CEST
Successfully generated the following models:
## Model name: AnonymousSchema1
// AnonymousSchema1 represents a AnonymousSchema1 model.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct AnonymousSchema1 {
    #[serde(rename="id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename="lumens", skip_serializing_if = "Option::is_none")]
    pub lumens: Option<i32>,
    #[serde(rename="sentAt", skip_serializing_if = "Option::is_none")]
    pub sent_at: Option<String>,
    #[serde(rename="additionalProperties", skip_serializing_if = "Option::is_none")]
    pub additional_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}
```

Though I note that the model isn't quite proper; the `#[serde(skip_serializing_if)]` annotation handles serialization, but not deserialization. You'd want `#[serde(default)]` as well so that the model can symmetrically deserialize its serialization output. 

Digression aside, it looks like the problem is related to the input file I gave it. It's not syntactic--the Zally linter passed my input file--but something there caused the Rust generator to abort without error messages.

**Comment by coriolinus** [comment]
Here's a moderately well minified example which shows the failure:

```yaml
openapi: "3.0.3" # Use older openAPI spec version due to a bug in Zally: https://github.com/zalando/zally/issues/1230
info:
  title: "Kudos Service"
  description: Keep track of company-internal gratitude.
  version: "0.1.0"

paths:
  "/kudos":
    post:
      operationId: "postKudos"
      requestBody:
        content:
          "application/json":
            schema:
              "$ref": "#/components/schemas/PostKudo"
        required: true
      responses:
        '201':
          description: "accepted kudo"
        default:
          content:
            "application/problem+json":
              schema:
                "$ref": "https://opensource.zalando.com/restful-api-guidelines/models/problem-1.0.1.yaml#/Problem"
      tags:
        - kudos
      security:
        - oauth:
          - kudos.write

components:
  schemas:
    SlackIdentifier:
      type: object
      properties:
        slack:
          type: string
      required:
        - slack

    PostKudo:
      type: object
      properties:
        kudos:
          "$ref": "#/components/schemas/SlackIdentifier"
        from:
          "$ref": "#/components/schemas/SlackIdentifier"
        reason:
          type: string
      required:
        - kudos
```

This isn't a real service--it comes from a company-internal presentation on OpenAPI--but it demonstrates the failure.

**Comment by jonaslagoni** [comment]
Solving https://github.com/asyncapi/cli/issues/616 will also solve this issue I think (not the wrong models, but just the interaction)

**Comment by chinma-yyy** [comment]
I think this issue is related to #616. Since there is no output on invalid file input currently. I used this file on my local machine with some changes from this PR #618 and it gave this output . 
![image](https://github.com/asyncapi/cli/assets/112387862/e03c1a14-7f30-4734-b959-ebb6da2ff546)

> But the CLI should definitely say what's wrong with the input 

Yes, @jonaslagoni the issue has been raised regarding this
