### ISSUE TITLE
help command is not working

### ISSUE THREAD

**Issue by prajjwalkapoor** [asyncapi/cli#559]
#### Describe the bug
`asyncapi help` is not recognized as a command. The functionality for the help is working with `asyncapi --help` but the recommendation says to use `asyncapi help` .

![image](https://github.com/asyncapi/cli/assets/68912239/f5f5a69d-5289-4cbd-9f0d-f21672d50305)

**Comment by Souvikns** [comment]
Yeah, we used to have a help command and then we removed it and now only allow help with the `--help` flag. With the new update with oclif to have an extra help command we have to use a plugin, so by default, we should have only the `--help` flag. 

> https://oclif.io/docs/help_classes

**Comment by sambhavgupta0705** [comment]
@Souvikns so we should remove the suggestion of `help` ?

**Comment by Souvikns** [comment]
I don't think we have any suggestions, for help, I am looking at the [usage docs](https://github.com/asyncapi/cli/blob/master/docs/usage.md) and I don't think we have anywhere specified about help command.

**Comment by derberg** [comment]
yeah, problem is I guess that we do not have control over the warning message that says `asyncapi help`

**Comment by sambhavgupta0705** [comment]
yes I searched for it in the repo but didn't find any instance.

**Comment by kaushik-rishi** [comment]
@Souvikns So we are not planning to add the help command right ?

**Comment by Souvikns** [comment]
Ok so the warning is coming from a package that we use called `@oclif/plugin-not-found` where it creates a log message for `help` command https://github.com/oclif/plugin-not-found/blob/470096ba538e89fea043fa7a712404a450da6204/src/index.ts#L18 I don't think we can change that and it is misleading to the user to have a warning saying them to use `asyncapi help` command which does not exist so we have two options really 

- create a help command 
- it is actually a [hook](https://oclif.io/docs/hooks) and we can write one for our use case and control the warning

what would be a good option?

**Comment by sambhavgupta0705** [comment]
IMHO 
>it is actually a [hook](https://oclif.io/docs/hooks) and we can write one for our use case and control the warning
 
 it is good to have only one command of help

**Comment by derberg** [comment]
I think we should go with the hook

**Comment by kaushik-rishi** [comment]
@derberg @Souvikns can i go ahead and work on this ?

**Comment by sambhavgupta0705** [comment]
@kaushik-rishi I would also like to work on this ,have gone through oclif docs and cli structure

**Comment by kaushik-rishi** [comment]
will we be hooking to the `command_not_found` event and then check if the command run was `asyncapi help` and then handle it ? If yes, how will we be handling it ?

**Comment by derberg** [comment]
since @sambhavgupta0705 was first in the issue, he is allowed to take it first 

@kaushik-rishi you can pick this one https://github.com/asyncapi/cli/issues/549 as it will also require digging into CLI and figuring how to provide meaningful error

**Comment by kaushik-rishi** [comment]
Sure thing 🙂

**Comment by kaushik-rishi** [comment]
@sambhavgupta0705 is.

**Comment by sambhavgupta0705** [comment]
> @sambhavgupta0705 is.

Yes,I am working on it .
We are waiting for @derberg approval

**Comment by Ayush2020012016** [comment]
Hi @sambhavgupta0705 are you still working on this.

**Comment by ayushnau** [comment]
@fmvilas 
can you tell me how should i go about this. means i need to update on pluggin-not-found. of which i dont have direct control.

**Comment by derberg** [comment]
@sambhavgupta0705 

> We are waiting for @derberg approval

sorry but what approval?

@ayushnau 
did you have a chance to see https://github.com/asyncapi/cli/issues/559#issuecomment-1560578163 ?

**Comment by ayushnau** [comment]
> @sambhavgupta0705
> 
> > We are waiting for @derberg approval
> 
> sorry but what approval?
> 
> @ayushnau did you have a chance to see [#559 (comment)](https://github.com/asyncapi/cli/issues/559#issuecomment-1560578163) ?

yes i started working on it.

**Comment by ayushnau** [comment]
https://github.com/asyncapi/cli/pull/843 @derberg

**Comment by AyushNautiyalDeveloper** [comment]
@Souvikns

**Comment by peter-rr** [comment]
@prajjwalkapoor @Souvikns
Should we considered this issue as solved by https://github.com/asyncapi/cli/pull/843 and then proceed to close it?
