### ISSUE TITLE
extend release workflow to throw errors when it fails

### ISSUE THREAD

**Issue by derberg** [asyncapi/cli#563]
#### Reason/Context

This workflows https://github.com/asyncapi/cli/blob/master/.github/workflows/upload-release-assets.yml runs on each release to build artefacts for different OS like linux and windows and uploads them to GitHub release (Assets section in https://github.com/asyncapi/cli/releases/tag/v0.40.6 for example)

Sometimes this workflow fails, for different reasons, sometimes timeout.

We need to know about it.

#### Description

Update https://github.com/asyncapi/cli/blob/master/.github/workflows/upload-release-assets.yml to make sure that on fail, it drops error to AsyncAPI slack.

just copy/paste https://github.com/asyncapi/cli/blob/master/.github/workflows/bump-homebrew-formula.yml#L30-L38 and of course adjust description

**Comment by meetagrawal09** [comment]
Hi @derberg, I would like to work on this issue : )
