### ISSUE TITLE
TS Error when run generation

### ISSUE THREAD

**Issue by Tenischev** [asyncapi/cli#574]
#### Describe the bug
TypeScript error when run generation from template/

#### How to Reproduce
1. Install node (tested with 16 and 18)
2. Install latest cli
3. Checkout asyncapi/java-spring-template
4. Run command `asyncapi generate fromTemplate tests/mocks/mqtt.yml @asyncapi/java-spring-template -o spring-output-test`
5. Error:
```
error TS6046: Argument for '--module' option must be: 'none', 'commonjs', 'amd', 'system', 'umd', 'es6', 'es2015', 'es2020', 'es2022', 'esnext', 'node12', 'nodenext'.
```

Additional details:
OS - Windows 11
```
asyncapi --version
@asyncapi/cli/0.40.8 win32-x64 node-v16.20.0
```

#### Expected behavior
No error when run generation from template

**Comment by derberg** [comment]
@Souvikns I think you have access to windows, can you help with this issue 🙏

**Comment by Tenischev** [comment]
here step by step drill down of commands, maybe this will help
![image](https://github.com/asyncapi/cli/assets/4137916/ab836439-f98e-47e9-936f-c373784c6de7)

**Comment by Souvikns** [comment]
OK, I am getting the same error on Mac as well.

**Comment by Souvikns** [comment]
The command is running on the codebase without any issue, but in production, it is not working, I checked and all other commands are working, might be something wrong with the generator.

Not a fix but you can run the command by passing `--module` flag run `asyncapi generate fromTemplate --module=none <rest of the parameters>`

**Comment by Tenischev** [comment]
> Not a fix but you can run the command by passing `--module` flag run `asyncapi generate fromTemplate --module=none <rest of the parameters>`

Nope
![image](https://github.com/asyncapi/cli/assets/4137916/f802a3b6-a881-4a5f-b529-34024109a593)

**Comment by derberg** [comment]
generator do not support `--module`, the error comes like from TS compiler I think

**Comment by Souvikns** [comment]
@Tenischev can you install typescript globally and try to run the command, it worked for me. 

<img width="756" alt="Screenshot 2023-05-23 at 4 19 11 PM" src="https://github.com/asyncapi/cli/assets/41781438/88f45957-e3da-4b9a-87dd-196069d69c50">

**Comment by derberg** [comment]
does it mean that `typescript` has to be moved to `dependencies`? it shouldn't be needed in production right? `typescript` should be required only in build time

**Comment by Souvikns** [comment]
> does it mean that `typescript` has to be moved to `dependencies`? it shouldn't be needed in production right? `typescript` should be required only in build time

typescript is just a compiler right we should not need it in production, no idea why this is happening. 

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html looking at this typescript could be used as a dependency

**Comment by derberg** [comment]
interesting

@Tenischev can you confirm if after `typescript` installation the issue was fixed?

**Comment by chinma-yyy** [comment]
**Working for me for the latest release**
<img width="750" alt="image" src="https://github.com/asyncapi/cli/assets/112387862/914b8574-2cf6-49f6-a972-f625f756fa46">

**Comment by derberg** [comment]
@Tenischev can you give it another try with latest 🙏

**Comment by Tenischev** [comment]
@derberg the problem still there
![image](https://github.com/asyncapi/cli/assets/4137916/d5f51743-98e6-4eec-8623-14abd4c9d33c)

**Comment by Souvikns** [comment]
@Tenischev did you install the CLI using npm?

**Comment by Souvikns** [comment]
Oh ok, I will then open a PR updating the package-lock. I was thinking that maybe packaging it into different installers creates a problem.

**Comment by derberg** [comment]
@Tenischev `0.51` that was just released should fix it 🤞🏼

**Comment by Tenischev** [comment]
@derberg I have a small update here. 
For the version `@asyncapi/cli/0.54.4 win32-x64 node-v18.17.1`.
CLI-Generator will work IF:
1. CMD is located in system volume (drive C for most Windows systems)
2. CMD is run with Administrator privileges.
![image](https://github.com/asyncapi/cli/assets/4137916/08a4d3d0-0537-4197-b288-17614912df96)
In other cases I receive the same error "error TS6046: ..."

**Comment by Amzani** [comment]
@Tenischev are you still experiencing this issue?
