### ISSUE TITLE
Integrate `asyncapi/diff` in the CLI

### ISSUE THREAD

**Issue by aayushmau5** [asyncapi/cli#58]
Since the [`asyncapi/diff`](https://github.com/asyncapi/diff/) library is, now, usable, we can integrate it into the AsyncAPI CLI.

My idea for the command usage:
```
asyncapi diff --files <file1.yml> <file2.yml>
asyncapi diff --contexts file1 file2
```

So, we need to think about some things:
- How to output the data
- Where to output the data
- The flags which will specify the type of output 

**How to output the data:**

For this, I'm thinking of having a flag `--<format>`. For started, we can provide output in JSON format. Then, in the future, we can go to HTML based output, markdown, etc.

```
asyncapi diff --files <file1.yml> <file2.yml> --json
asyncapi diff --files <file1.yml> <file2.yml> --html
```
**Where to output the data:**

Now the question arises, where do we output the data. In a file? In the terminal?
Looking at OpenAPI [diff](https://github.com/OpenAPITools/openapi-diff) tool, we can also provide an **optional** `<file>` option along with `--<format>` flag. `--<format> <file>`. The default output will be in the terminal.

```
asyncapi diff --files <file1.yml> <file2.yml> --json <file-output>
asyncapi diff --files <file1.yml> <file2.yml> --html <file-output>
```

**The flags which will specify the type of output:**

Since the diff library provides a bunch of helpers function which provide different output(ex. only `breaking` changes, only `non-breaking` changes), we can provide a flag to do this through the CLI. The default will provide the full output.
ex.
```
asyncapi diff --files <file1.yml> <file2.yml> --json <file> --breaking # for breaking changes
asyncapi diff --files <file1.yml> <file2.yml> --json <file> --non-breaking # for non-breaking changes
```

Any thoughts on this idea?

**Comment by derberg** [comment]
Hey, there is a topics covered here that are important no matter if we work on diff or not: the output

atm, library outputs on terminal only. There is no `--output` option so far. This is independent from `diff` as we need output to file functionality in many different commands, for relations finding or for optimizations. This needs to be implemented separately

regarding optional flags, we so far tend to always have name, so instead of `--json` do `--format=json`

as if it comes to `asyncapi diff --files <file1.yml> <file2.yml>`, we have some discussions in other issue that are kind of going the direction of getting rid of `--file` or `--files` flag, as flags are options, they are optional, while in case of file, it is must have, not optional, it is kinda a center of all the things

**Comment by aayushmau5** [comment]
> atm, library outputs on terminal only. There is no --output option so far. This is independent from diff as we need output to file functionality in many different commands, for relations finding or for optimizations. This needs to be implemented separately

Got it. 

> regarding optional flags, we so far tend to always have name, so instead of --json do --format=json

:+1: 

> as if it comes to asyncapi diff --files <file1.yml> <file2.yml>, we have some discussions in other issue that are kind of going the direction of getting rid of --file or --files flag, as flags are options, they are optional, while in case of file, it is must have, not optional, it is kinda a center of all the things

So I guess, we will have

```
asyncapi diff <file1> <file2l>
```
for file.

**Comment by derberg** [comment]
> So I guess, we will have
asyncapi diff \<file1> \<file2l>
for file.

yup, but with clear indication which one is checked against the other, I mean if file1 is checked against file 2? or the opposite

the part about `file` flag I mentioned (that it will be removed) is something that @Souvikns will work on https://github.com/asyncapi/cli/issues/37#issuecomment-908126687

**Comment by aayushmau5** [comment]
Now that the migration to Ocliff is done, I will start working on this. Hope to make a PR by the end of this week.

**Comment by Souvikns** [comment]
Yeah sure, let me know if you need anything.

**Comment by aayushmau5** [comment]
@Souvikns Does the CLI have the ability to output data into files? Since, Lukasz said that this functionality should be a separate implementation independent of the command.

**Comment by Souvikns** [comment]
hmm, it doesn't. 
>  Lukasz said that this functionality should be a separate implementation independent of the command.

Yeah, you should create a wrapper around diff and connect it with CLI. For a little context, the CLI is [this](https://github.com/asyncapi/cli/tree/master/src/commands), so you just need to create a function wrapping your `diff` library and create a new command for it. 

Can you give me some context on what kind of output diff is generating? As of now, all output is printed in the console itself.

**Comment by aayushmau5** [comment]
> Can you give me some context on what kind of output diff is generating? As of now, all output is printed in the console itself.

Right now I'm just generating the default json output.

**Comment by magicmatatjahu** [comment]
Solution that we should consider for that issue https://github.com/asyncapi/community/issues/249 It's only an idea so please treat it as suggestion, not final approach. Feel free to comment :)

**Comment by aayushmau5** [comment]
Should we close this issue now that we have integrated diff in CLI?
