### ISSUE TITLE
Enable SonarCloud scans

### ISSUE THREAD

**Issue by derberg** [asyncapi/cli#60]
We scan all AsyncAPI project with SonarCloud to check for code smells, security issues and other things like it. We use their official bot for it. In case of this project we cannot do it -> https://community.sonarsource.com/t/project-is-not-analysed-as-there-is-no-code-but-actually-there-is/48747/4. We would have to make an exception here and configure dedicated GitHub Action.

So my question is:
1. Do we really need `@sindresorhus/tsconfig` what is the advantage and what we loose once we remove it?
2. If we really need this configuration, how about we commit it to the repo? it is just one file, no dev dependencies. I think in this case it is acceptable to have this dev dep committed into the repo

What is your opinion folks? I personally do not like exceptions, they complicate lives, so prefer to use one of above solutions instead of treating CLI as a special project

**Comment by Souvikns** [comment]
We don't really need `@sindresorhus/tsconfig` we can just create our own config.

**Comment by derberg** [comment]
@Souvikns thanks!

@jotamusik can you share your opinion? you added it after all

@magicmatatjahu anything from your side sir

**Comment by magicmatatjahu** [comment]
Together with @jonaslagoni we one time talked about creating something like `template-for-js-project` with `template-for-ts-project` alongside with our preferred `tsconfig.json`, but not now. I have no opinion here. If @Souvikns and @jonaslagoni think that it may be removed, just remove it, or copy the content from `@sindresorhus/tsconfig` to repo's `tsconfig.json` :)

**Comment by derberg** [comment]
it is already done, @sindresorhus/tsconfig removed, and check run
