### ISSUE TITLE
Failed to create a template with the glee framework 

### ISSUE THREAD

**Issue by afzal442** [asyncapi/cli#667]
#### Describe the bug
when I try out, `asyncapi new glee`, I am getting error, but `asyncapi new` works for me. like after that I have to mention the yaml file.

the error is as such `Error: ENOENT: no such file or directory, lstat '/usr/local/share/nvm/versions/node/v19.9.0/lib/node_modules/@asyncapi/cli/create-glee-app/templates/default'`

#### How to Reproduce
Steps to reproduce the issue.

- Install asyncapi cli with `npm install -g @asyncapi/cli`
- Run `asyncapi new glee`

npm version: 9.6.3
node version: v19.9.0

**Comment by afzal442** [comment]
// @jonaslagoni @KhudaDad414

**Comment by Souvikns** [comment]
@peter-rr

**Comment by Souvikns** [comment]
I am getting the same error as well @afzal442, seems like this is coming from https://github.com/asyncapi/cli/blob/5aa4bbe3df0517feda06908909824f478206c241/src/commands/new/glee.ts#L23

**Comment by afzal442** [comment]
Aha, thanks @Souvikns for that if I was only getting this err.

**Comment by chinma-yyy** [comment]
> I am getting the same error as well @afzal442, seems like this is coming from
> 
> https://github.com/asyncapi/cli/blob/5aa4bbe3df0517feda06908909824f478206c241/src/commands/new/glee.ts#L23

Actually in the release the `create-glee-app` directory is not shipped. Maybe some release configurations?
![image](https://github.com/asyncapi/cli/assets/112387862/413634ee-66b6-4318-bfaf-7da09c4a2a9e)

**Comment by afzal442** [comment]
For the time being, we can try this https://github.com/asyncapi/cli#set-up-development-environment or add this missing dir.

// @Souvikns

**Comment by peter-rr** [comment]
Thanks @afzal442 😄 
Yeah, in dev environment it's working fine, so you can run `./bin/run/ new glee` while I'm working on the fix. I'll let you know when it's ready!

**Comment by Souvikns** [comment]
@afzal442 now that pr is merged can you update the CLI and check if the issue persists?
