### ISSUE TITLE
Update CODEOWNERS file

### ISSUE THREAD

**Issue by peter-rr** [asyncapi/cli#668]
#### Reason/Context
I would like to be able to review and merge commits into the CLI to help out.
Let me know what you think :)

#### Description
CODEOWNERS file needs to be updated in that case: https://github.com/asyncapi/cli/blob/5aa4bbe3df0517feda06908909824f478206c241/CODEOWNERS

**Comment by chinma-yyy** [comment]
> I feel like a lot of contributors don't know this, we should add it in our contributor guide or something.

Yes, I also did not know till now.

**Comment by derberg** [comment]
> Yes, I also did not know till now.

yeah, we definitely need more docs and luckily we now have a place where to put them https://www.asyncapi.com/docs/community. Documenting it is on the list in https://github.com/asyncapi/website/issues/903, we just need someone to contribute

**Comment by derberg** [comment]
> @derberg if you are asking that should we make @peter-rr maintainer or not then I vote yes

no no, anyone can be maintainer, and if @peter-rr goal is to be one, we should support that. Actually the more maintainers, the easier maintenance for those that are outnumbered 😄 

But to be a maintainer you need to show that you can actually be one, and other maintainers can trust you accepting PR (enabling them to be merged). Perfect example is @akshatnema that became maintainer for website, by not only contributing features but also participating in review big time. This way I could see what he looks at, how he approach people and I 💯 trust he accepts PRs and the direction of the project is understood.

So, I'm definitely ok, but not now. For me it is important that @peter-rr shows his activity in:
- review of new PR. The best if he now regularly watch PRs, and acts as first reviewer to new incoming PRs
- jumps in review in some existing PRs
- look into some bugs and tries to help solving them, especially if they are related to features that he added
- look into some old issues and triage them on what is their status

I hope you know what you mean 😄 
Thoughts folks?

PS. I think it is a first time someone openly asks about it, and it can end up as a document/guide for maintainer-candidates

**Comment by peter-rr** [comment]
Alright! Thanks for the detailed explanation 👌 
I totally agree with that criteria in order to be a maintainer. It does make sense to me! 👍
