### ISSUE TITLE
add `.prettierignore` to prevent autoformatting 

### ISSUE THREAD

**Issue by chinma-yyy** [asyncapi/cli#682]
**Inspired from this [PR](https://github.com/asyncapi/website/pull/1934)**

Many new contributors just like me face this problem where prettier just auto formatted the code and faced many linting issues.

**Comment by depleur** [comment]
Hey, I'll add this real quick.

**Comment by derberg** [comment]
yeah, it is hitting maintainers recently 😅 

https://github.com/asyncapi/.github/pull/253 will fix it for all, we just need to figure if we push it only to repos that explicitly want it, or push it to all but first identify what repos do not want it
