### ISSUE TITLE
Can't bundle yaml file with json output file

### ISSUE THREAD

**Issue by andrebraghini** [asyncapi/cli#699]
#### Describe the bug
I need to bundle a yaml file, but I want a json output format.
When a provide output with a json extension, I get an error.

#### How to Reproduce
```bash
asyncapi bundle asyncapi.yaml -o asyncapi.json
```

I'm getting this message:
```bash
TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
```

#### Expected behavior
Generate a json bundle file without errors.

#### Workaround

If I provide a yaml file with no extension as input, I can write the output to a new file as expected:
```bash
asyncapi bundle asyncapi_file_without_extension > asyncapi.json
```

**Comment by derberg** [comment]
Thanks for the issue.

@Souvikns hey can you have a look 🙏

**Comment by Souvikns** [comment]
I was able to reproduce the error and this is why it is happening:

https://github.com/asyncapi/bundler/blob/70a64bb6516af5c0ca1a1ea8ee85ffeec3668d1b/src/document.ts#L39 in bundler `document.json()` returns an object.
