### ISSUE TITLE
AbortSignal error caught while running the server from glee cli

### ISSUE THREAD

**Issue by afzal442** [asyncapi/cli#708]
#### Describe the bug

```
> glee-hello-world@0.1.0 dev
> glee dev

 TS Compiling TypeScript sources...
 TS node_modules/@types/node/globals.d.ts:72:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.
```

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

Run `asyncapi new glee`
Get to the project dir
Run `npm run dev` after npm i

@KhudaDad414 @Souvikns

**Comment by afzal442** [comment]
Hi maintainers, can I get a signal here if I this is relevant? if any error occurs?

**Comment by Souvikns** [comment]
Yeah, I am getting the same error, for some reason when I install `@types/node` it runs can you manually create a project and see if you are getting the same error?

**Comment by KhudaDad414** [comment]
@afzal442 @Souvikns I can't reproduce this:
<img width="541" alt="Screenshot 2023-08-29 at 10 07 22" src="https://github.com/asyncapi/cli/assets/32505158/28f41a48-37c5-460a-a2c5-d0dbd10fe993">
I am using node 18 on Mac

**Comment by afzal442** [comment]
Let's e-meet sometime. 😄

**Comment by peter-rr** [comment]
@afzal442 
I cannot reproduce the error either:

![Monosnap 266617494-97b058fd-7066-46fc-91b2-940ed01a86bd png (621×240) 2023-09-08 15-02-34](https://github.com/asyncapi/cli/assets/81691177/a90d4004-90e4-4927-9f7c-0aaccace7f83)


I guess the issue has already been solved with this [fix](https://github.com/asyncapi/cli/pull/783), related to what @Souvikns commented above.

**Comment by Souvikns** [comment]
Yeah, we can close this, It has been fixed with this https://github.com/asyncapi/cli/pull/783. 

@afzal442, update your CLI and it should work now.

**Comment by afzal442** [comment]
That's cool. I checked it yesterday. Let me do it again

**Comment by afzal442** [comment]
It's working fine as on asyncapi 0.54.7
