### ISSUE TITLE
Add a new flag to set context when it is created 

### ISSUE THREAD

**Issue by Souvikns** [asyncapi/cli#726]
#### Reason/Context

To create a new context and then set it as current we have to run two commands namely 
- `asyncapi config context add`
- `asyncapi config context use`

We could really add a flag in the `context add` command so that we automatically set the config as current when we are creating it, so something like this 

```
asyncapi config context add [context-name] [file-path] --set-current
```

#### Description

I think this is preet simple as we just have to add a new flag in [here](https://github.com/asyncapi/cli/blob/dc99a3d376784babb710be2fd872f291bccdd3b5/src/commands/config/context/add.ts#L7), for more information on how to create flags in Oclif commands read [here](https://oclif.io/docs/flags)

https://github.com/asyncapi/cli/blob/dc99a3d376784babb710be2fd872f291bccdd3b5/src/commands/config/context/add.ts#L7

**Comment by AnishKacham** [comment]
Hi @Souvikns. I'd like to try my hand at this issue if that's ok. ^_^

**Comment by AnishKacham** [comment]
I wanted to see the behavior of the context operations but I ran into this issue.
https://github.com/asyncapi/cli/issues/751
