### ISSUE TITLE
Version Checking using CLI on Installation

### ISSUE THREAD

**Issue by SrijanShovit** [asyncapi/cli#728]
#### Reason/Context

- What is the motivation? 

On installation of any package, I think it's a good practice to have a way for users to check installation using the checking version. Most of the packages provide a way to do this by providing a -v or --v or -version type of flags. However, there is none in the async API CLI tool.

- Why we need this improvement?

So what we can do is to include a flag for version checking which will be helpful for users to check if installation was complete and also check the versions. Right now, there are not many things associated with CLI command. But if later there are lots of things to do with CLI and the user has to check installation or version via asyncapi command without any flag, that can be irritating.

#### Description

- What changes have to be introduced?

We need to include a -v flag to show the version where all other flags are defined.

- Will this be a breaking change?

No, it won't be a huge change but will be nice for users for sure.

<img width="960" alt="async api" src="https://github.com/asyncapi/cli/assets/86592220/343eba94-22e0-4907-9e19-4db96dc86fd3">

**Comment by Souvikns** [comment]
@SrijanShovit we can check the version but for some reason `-v` does not work but `asyncapi --version` is working. This is handled by oclif no idea why `-v` is not working.

**Comment by Amzani** [comment]
still relevant
