### ISSUE TITLE
Failing context operations like add, use, list, etc.

### ISSUE THREAD

**Issue by AnishKacham** [asyncapi/cli#751]
Context operations do not work even after initializing context

#### How to Reproduce
Create an empty directory, and spin up a sample asyncapi spec document.
for this I used the sample [mentioned]( https://gist.github.com/AnishKacham/f7cf6aadaa11c436d40f9910bef51a60
) in the [docs](https://www.asyncapi.com/docs/tutorials/create-asyncapi-document) :

`asyncapi config context init`
you should see a `.asyncapi-cli` file get created with the following content: 
```
{"store":{}}
```
now running `asyncapi config context add foo ./asyncapi.yaml` gives the following message even if context is initialized already
```
You have no context file configured. Run "asyncapi config context init" to initialize it.
```
- Screenshots
![image](https://github.com/asyncapi/cli/assets/79566582/c6a11442-a857-4764-b399-4817a1545126)

- Link to GitHub repository with project that has issues
  - https://github.com/asyncapi/cli
  
#### Expected behavior
- Context should be added to the `.asyncapi-cli` file

**Comment by derberg** [comment]
@aeworxet hey any ideas?

**Comment by AnishKacham** [comment]
update on this issue. The command works perfectly fine if I'm building cli locally and then using it as:
 ```
./bin/run config context add foo .\asyncapi.yaml
```

**Comment by derberg** [comment]
@AnishKacham when you tested a binary, how did you install it? `npm install @asyncapi/cli -g` or?

**Comment by AnishKacham** [comment]
> @AnishKacham when you tested a binary, how did you install it? `npm install @asyncapi/cli -g` or?

Yes. That is indeed how I installed asyncapi cli. the `./bin/run` was from cloning the repository and running `npm run build`

**Comment by derberg** [comment]
getting the same with binary installed over npm:

```bash
$ asyncapi --version
@asyncapi/cli/0.52.3 darwin-x64 node-v16.13.0

$ asyncapi config context init
Initialized context /{...}/template-for-generator-templates-asyncapi-fork/.asyncapi-cli

$ cat .asyncapi-cli
{"store":{}}

$ asyncapi config context add dummy test/fixtures/dummy.yml
You have no context file configured. Run "asyncapi config context init" to initialize it.

**Comment by Souvikns** [comment]
I think it is working for me
![Screenshot 2023-08-10 at 4 29 10 PM](https://github.com/asyncapi/cli/assets/41781438/5fa08542-2371-494e-a820-e1c4dd674dbf)

**Comment by aeworxet** [comment]
```
$ npm install @asyncapi/cli -g
[installed]

$ asyncapi --version
@asyncapi/cli/0.52.3 linux-x64 node-v18.9.0

$ asyncapi config context init
Initialized context /home/aeworxet/tmp_test/.asyncapi-cli

$ cat .asyncapi-cli
{"store":{}}

$ asyncapi config context add dummy test/fixtures/dummy.yml
Added context "dummy".

You can set it as your current context: asyncapi config context use dummy
You can use this context when needed by passing dummy as a parameter: asyncapi validate dummy

$ asyncapi config context list
dummy: test/fixtures/dummy.yml
```

```
$ node -v
v18.9.0

$ npm -v
8.19.2

host Linux
Ubuntu 20.04.6 LTS
```
@derberg @AnishKacham 
Please share whether you use **host** Linux or some bash for Windows, like `Git Bash`/`Cygwin`.

**Comment by AnishKacham** [comment]
host Windows
Using Powershell
```
$ node -v
v20.4.0

$ npm -v
9.7.2

$ asyncapi --version
@asyncapi/cli/0.52.3 win32-x64 node-v20.4.0
```
host Win11
via powershell
Not using `Git Bash` / `Cygwin`

 
" `add` works when you do it from location that is not git repo
so `add` fails only when you `init` for the repo. So probably loading context from repo root is problematic "

as discovered by @derberg 
cc : @aeworxet @Souvikns 

I've checked this and it seems like it is the issue.

**Comment by aeworxet** [comment]
I was able to reproduce this issue only when I ran in `Git Bash` on Windows
```
$ npm install @asyncapi/cli -g
$ asyncapi config context init
$ asyncapi config context add dummy test/fixtures/dummy.yml
```
If I rebuild locally and run
```
$ npm run build
$ ./bin/run config context init
$ ./bin/run config context add dummy test/fixtures/dummy.yml
```
everything works.
So the issue is in combination of Windows and the prebuilt binary, and it doesn't depend on the version of Node.js.

```
$ node -v
v14.17.6
```

UPD.
Strange observation:
When I run in `Git Bash` on Windows
```
$ asyncapi config context init
$ asyncapi config context add dummy test/fixtures/dummy.yml
```
in the root of cloned `cli` repo I GET reproduction.
When I run same commands in another directory which also contains directory `.git`, I DO NOT get the reproduction.

**Comment by aeworxet** [comment]
Diff shows no difference between prebuilt and locally built packages.

![image](https://github.com/asyncapi/cli/assets/16149591/fa5dbeb5-90ec-4eaa-bc4e-a0e18c662b47)

**Comment by aeworxet** [comment]
I have narrowed the search for this bug.
The bug is not reproduced when file `oclif.manifest.json` is removed from prebuilt `@asyncapi/cli` package.
When `cli` package is built locally it does not include `oclif.manifest.json` file, that is why the bug is not reproduced when using the locally built package.

**Comment by derberg** [comment]
oh lovely, we at least can reproduce now on local. The `oclif.manifest.json` must stay. Maybe we should consider to generate it on local too, and just add to `.gitignore`

**Comment by derberg** [comment]
just opened a PR with fix that should solve the problem, at least works on my machine 😄

**Comment by aeworxet** [comment]
Works on my machine too.
@AnishKacham does change from PR https://github.com/asyncapi/cli/pull/778 work on your machine?

**Comment by AnishKacham** [comment]
> Works on my machine too. @AnishKacham does change from PR #778 work on your machine?

Yess. That works as expected on my machine. 🎉

**Comment by aeworxet** [comment]
The code works on three machines in different tech environments, in three different states. Should be good to merge.
