### ISSUE TITLE
Better way to handle Error messages 

### ISSUE THREAD

**Issue by Souvikns** [asyncapi/cli#76]
I and @magicmatatjahu were talking about [this](https://github.com/asyncapi/cli/pull/72#discussion_r712774008). We can improve the way error messages are handled.  Right now there are a bunch of `try/catch` blocks making the code messy. Also, the error is generated from separated places. Would be better to have a discussion on this.

**Comment by magicmatatjahu** [comment]
My main idea would be to cache (buffor) errors and display them at the end of command execution. Maybe something like event sourcing would help.

**Comment by Souvikns** [comment]
Should we close this, oclif is handling this.
