### ISSUE TITLE
node_modules installation error

### ISSUE THREAD

**Issue by chinma-yyy** [asyncapi/cli#771]
#### Describe the bug
During the setup im getting this error 
![image](https://github.com/asyncapi/cli/assets/112387862/0c86de37-da81-4598-a6b4-e78e0b2582f9)

#### How to Reproduce
clone the repo and npm install

- Screenshots
- Link to GitHub repository with project that has issues
- Files that can help reproduce the issue, like your AsyncAPI file, either paste inside the issue in a code block or in a sharable [gist](https://gist.github.com/)

#### Expected behavior
Should install all the dependencies

**Comment by chinma-yyy** [comment]
Is it because of my node version or any dependency issue??

**Comment by derberg** [comment]
I'm on node 16.13 and npm 8.1 and fresh installation works like a charm. What version or node and npm you're using?

**Comment by chinma-yyy** [comment]
> I'm on node 16.13 and npm 8.1 and fresh installation works like a charm. What version or node and npm you're using?

I was using 18.17 then i used 20 using nvm and now back to 18.17 and it works fine dont know why!! Just engineer things :laughing:
