### ISSUE TITLE
Add `start studio` command

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/cli#78]
In https://github.com/asyncapi/studio/issues/80 has been proposed to add the `start studio` command, which:

- should start local instance of our Studio (first we have to implement it)
- should start local instance of API - https://github.com/asyncapi/studio/issues/86
- should run a simple server that would support the filesystem to be able to read/write content from/to files

For example, a user could use this command to edit an AsyncAPI document in their favorite IDE, but could also see immediatelly changes in the rendered html-template. The local server would see the changes in the AsyncAPI document - including references to local files - and then pass such a file to the Studio, where the user could use UI to do necessary things like model generation, optimizations, check for changes between versions, etc.

**Comment by derberg** [comment]
we should definitely make sure to drop a message that started server should not be used on production 😄

**Comment by magicmatatjahu** [comment]
Right, but I understand that from the concept of the command 😄

**Comment by fmvilas** [comment]
I'm closing this issue as it's already implemented in #102
