### ISSUE TITLE
Support protobuf schema parser

### ISSUE THREAD

**Issue by smoya** [asyncapi/cli#785]
#### Reason/Context

https://github.com/asyncapi/protobuf-schema-parser is a Schema parser for protobuf. Adding support for it is needed in order to generate using documents that contain schemas in that format.

#### Description
In order to support that, we need to add that to the dependencies + register it in the Parser as we do with the rest [here](https://github.com/asyncapi/cli/blob/d143cf628b600a969a99a08ab2d7a38e29d1e593/src/parser.ts#L3C1-L28).

cc @GreenRover

**Comment by derberg** [comment]
already done
