### ISSUE TITLE
Restrict the CLI to create only create file having yml and yaml extension.

### ISSUE THREAD

**Issue by AayushSaini101** [asyncapi/cli#794]
#### Reason/Context
Please try answering a few of those questions
- Why do we need this improvement?

Currently, the CLI is creating files of any type of extension like exe or any type of invalid extension it would be to restrict the CLI to create files of invalid extension. It will help in many cases, for example, formatting plugins cannot able to ident invalid files. 

![image](https://github.com/asyncapi/cli/assets/60972989/ac95b1e6-2708-41ab-94e0-9581d3775fde)

- How will this change help?

It will increase the developer experience:

- What is the motivation? 

#### Description
Please try answering a few of those questions

- Will this be a breaking change?

No. it will not break the existing feature 

- How could it be implemented/designed?

Using Certain checks

**Comment by Souvikns** [comment]
@AayushSaini101, Yeah actually this is a bug, You can open a PR for this if you want, I think it would be better to have a check for the `--file-name` flag  and allow only

- `yml`
- `yaml`
- `json`
