### ISSUE TITLE
feat: need to Implement of catch block in the various commands

### ISSUE THREAD

**Issue by AayushSaini101** [asyncapi/cli#800]
#### Reason/Context
Please try answering a few of those questions
- Why do we need this improvement?

Currently, there are empty catch blocks present in the files that need to implement. 

![image](https://github.com/asyncapi/cli/assets/60972989/b2003989-5ab1-443a-8a29-f800340f063b)

- How will this change help?

It is always good to write proper catch block to handle the exceptions properly. 

#### Description
Please try answering few of those questions
- Will this be a breaking change?
No, it will not break any functionality of the CLI.

**Comment by Ayush2020012016** [comment]
@AayushSaini101 will create the file in the catch block. what should be the content of that file.

**Comment by AyushNautiyalDeveloper** [comment]
@AayushSaini101 I am working on it.

**Comment by Ayush2020012016** [comment]
![image](https://github.com/asyncapi/cli/assets/78146753/7ce91814-0c56-4217-94de-e4377eded49e)

i am wondering if there is no file then we must create a new one. but then what the line no. 164 is doing it doing the same.

**Comment by Ayush2020012016** [comment]
thanks for the reply in slack.

**Comment by Amzani** [comment]
@ayushnau any updates? 
cc @AayushSaini101
