### ISSUE TITLE
Testing Redocly CLI for linting AsyncAPI documents.

### ISSUE THREAD

**Issue by ayushnau** [asyncapi/cli#815]
#### Reason/Context
Please try answering few of those questions

- How will this change help?
It would be better if we have linter for the AsyncAPI documents. 

#### Description
Please try answering few of those questions

- Will this be a breaking change?
 No, this will not be a breaking change.

**Comment by Ayush2020012016** [comment]
![image](https://github.com/asyncapi/cli/assets/78146753/1b2d6b2f-6a8c-43bd-934e-b54f96f196f0)

**Comment by lornajane** [comment]
This issue I think relates to the Redocly CLI, not the AsyncAPI CLI. The repo for the Redocly project is here https://github.com/Redocly/redocly-cli/.

Please check out the guide to get started using AsyncAPI linting in Redocly CLI:  https://redocly.com/docs/cli/guides/lint-asyncapi/

**Comment by derberg** [comment]
@ayushnau please specify what is the goal of this issue? how different this functionality is from `asyncapi validate`?

@lornajane thanks for the link to redocly 🙇🏼
