### ISSUE TITLE
The new glee command is generating a 2.1.0 document

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/cli#829]
#### Describe the bug
The `new glee` command is creating a new project in which the `asyncapi.yaml` is using the `2.1.0` version of the spec.

#### How to Reproduce
Just run `asyncapi new glee` and check the `asyncapi.yaml` file inside the `project` folder.

#### Expected behavior
It should be on the latest version. As of now, on 2.6.0.

**Comment by ayushnau** [comment]
@fmvilas  looking into this.

**Comment by ayushnau** [comment]
@fmvilas  https://github.com/asyncapi/cli/pull/833

**Comment by thedeeppp** [comment]
This issue has closed, right @fmvilas?

**Comment by kenilJoshi** [comment]
is the issue Closed @fmvilas ?

**Comment by fmvilas** [comment]
Kinda. It should be 3.0.0 now but @Souvikns is on it already.
