### ISSUE TITLE
Update the missing arguments message

### ISSUE THREAD

**Issue by Souvikns** [asyncapi/cli#86]
https://github.com/asyncapi/cli/blob/9d385168166957be89cbc52692b69017c07d1dda/src/messages.tsx#L8

It should say what arguments are missing, For example for the command `asyncapi context add <context-name> <spec-path>`
The message should be something like this. 
```
Missing arguments: context-name
run asyncapi <command> --help to know more. 
````

A couple of things needs to be changed - 
- https://github.com/asyncapi/cli/blob/9d385168166957be89cbc52692b69017c07d1dda/src/messages.tsx#L8 it has to be converted into a function that would accept `parameter_name` and `command`. 
- Then update the Error class https://github.com/asyncapi/cli/blob/9d385168166957be89cbc52692b69017c07d1dda/src/hooks/context/models.ts#L37-L42 
- and finally updated all the instances where this error has been thrown.

**Comment by mihirterna** [comment]
I would like to work on it, can you please assign it to me ?

**Comment by derberg** [comment]
@mihirterna done
