### ISSUE TITLE
fail-severity warn info  

### ISSUE THREAD

**Issue by AliaksandrShamchonak** [asyncapi/cli#861]
#### Describe the bug
The fail-severity doesn't generate an exit code 1 even for the warn/info severity.  
@asyncapi/cli/0.58.12 linux-x64 node-v18.16.0

#### How to Reproduce
`asyncapi validate schema.yaml --fail-severity=warn`
![image](https://github.com/asyncapi/cli/assets/51114482/017d97af-281e-4ae5-b389-d7d0f4a98b0e)
`echo $?`
`0`

#### Expected behavior
The exit code should be `1` but got `0`.

**Comment by fauzank339** [comment]
Hello, is this issue still open, when I try to reproduce it. It is correctly validating the file.

![image](https://github.com/asyncapi/cli/assets/50906187/4aa1a9ff-fdd5-49e8-8465-afc64316ae47)

**Comment by AliaksandrShamchonak** [comment]
> Hello, is this issue still open, when I try to reproduce it. It is correctly validating the file.
> 
> ![image](https://private-user-images.githubusercontent.com/50906187/294740924-4aa1a9ff-fdd5-49e8-8465-afc64316ae47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDEzNzksIm5iZiI6MTcwNDcwMTA3OSwicGF0aCI6Ii81MDkwNjE4Ny8yOTQ3NDA5MjQtNGFhMWE5ZmYtZmRkNS00OWU4LTg0NjUtYWZjNjQzMTZhZTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA4MDQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjODY3ODY0NGIwODQ5ZTM3ZTkxNWJjNjEyYjkxMjNhMTAzYWI2N2Y2MWNiZWQxYmQzZjE3MzU3MzQwOWUxMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X3fAQpdRLubp2DMvenG-Ni2qwDno6F-ut9aIPzS4m88)

The schema.yaml must have an issue to reproduce the bug. Please modify your schema.yaml, for example. remove the field "id" and check again.

**Comment by JarnoRFB** [comment]
I am seeing the same behavior even for `--fail-severity=error` with errors in my spec. The coloring of the report summary is correct (red), but the exit code is always `0` making it difficult to use the `validate` command in CI.
