### ISSUE TITLE
Micro CLI for each tool

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/cli#883]
#### Reason/Context
I have been wondering for some time whether it's possible for us to do micro-CLIs for each individual tool, and then bundle them all together in the AsyncAPI CLI?

For example with Modelina, it supports multiple inputs not just AsyncAPI, but the AsyncAPI CLI is of course solely focused on those type of documents. So we would have to create a separate CLI just for this, but there is gonna be quite big overlap in the generators, as they will 100% be the same across that separated CLI and the AsyncAPI CLI. So my idea was that all Modelina-specific CLI commands where released in Modelina, and all the AsyncAPI CLI would have to do is install the dependency and extend the existing oclif commands 🤔 

Do you think that would be possible?

**Comment by derberg** [comment]
We never tried it so not really sure if this is possible, sorry.

What I definitely think is that it will add complexity here for sure :)
