### ISSUE TITLE
generator features 

### ISSUE THREAD

**Issue by Souvikns** [asyncapi/cli#9]
CLI will be porting all the functionalities from the generator CLI, so as of now the supported options and commands by the generator CLI are 

#### arguments
`<asyncapi> <template>`
`<asyncapi>` - path to the asyncapi file 
`<template>` - template name 

#### Options
- `-d, --disable-hook [hooks...]` disable a specific hook type or hooks from a given hook type
- `--debug` to enable specific errors in the console 
- `-i, --install` installs the template and its dependencies (defaults to false)
- `-n, --no-overwrite <glob>` glob or path of the file(s) to skip when regenerating
- `-o, --output <outputDir>` directory where to put the generated files (defaults to current directory)
- `-p, --param <name=value>` additional param to pass to templates
- `--force-write` force writing of the generated files to given directory even if it is a git repo with unstaged files or not empty dir (defaults to false)
- `--watch-template`  watches the template directory and the AsyncAPI document, and re-generate the files when changes occur. Ignores the output directory. 
- `--map-base-url <url:folder>`  maps all schema references from base url to local folder

**Comment by magicmatatjahu** [comment]
Still valid. We need the generator command in our cli.
