### ISSUE TITLE
Glee templates don't update to the latest version of Glee

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/cli#923]
#### Describe the bug
When a new version of Glee is out, the `@asyncapi/glee` dependency is updated but the `@asyncapi/glee` dependency of the Glee templates is not.

#### Expected behavior
It should update automatically when a new version of Glee is out.

**Comment by MahendraDani** [comment]
@fmvilas Would you please guide me how can this issue be solved?

**Comment by fmvilas** [comment]
I think either @KhudaDad414 or @derberg can guide you better. I'm not fully aware of how CI works.

**Comment by KhudaDad414** [comment]
@MahendraDani we use https://github.com/asyncapi/.github/blob/master/.github/workflows/bump.yml workflow to update the package of dependent projects. which in turn uses https://github.com/derberg/npm-dependency-manager-for-your-github-org which is developed by @derberg to update the dependent packages. not sure if it is something that this action is designed to do. I mean update packages in custom paths. 🤔

**Comment by Shurtu-gal** [comment]
@fmvilas @KhudaDad414 I guess this issue can be shifted to @derberg's action.
Found the error ⬇️ 

https://github.com/derberg/npm-dependency-manager-for-your-github-org/blob/26a4f13d740254719971325046822a169aaa7441/lib/api-calls.js#L8-L10

The action is getting a correct list of file paths however as the repos are grouped a repo with multiple hits has some file paths which are ignored.

This can be seen [here](https://github.com/asyncapi/glee/actions/runs/7128321235/job/19410056520#step:4:10) which only lists 4 repos leading to an update of only 4 filepaths. While [this rest API](https://api.github.com/search/code?q=%22@asyncapi/glee%22%20user:asyncapi%20in:file%20filename:package.json) call lists 17 of them.

If you want I can raise an issue and resolve it at the action level 🤟🏻

**Comment by derberg** [comment]
@Shurtu-gal please go ahead 🙏
