### ISSUE TITLE
Html generated by docker asyncapi/cli does not show anything

### ISSUE THREAD

**Issue by marcindulak** [asyncapi/cli#924]
#### Describe the bug

Html generated by docker asyncapi/cli does not show anything

#### How to Reproduce

I'm following https://www.asyncapi.com/docs/tools/generator/usage#generator-cli, and applying this fix https://github.com/asyncapi/cli/issues/844

```
curl -sLO https://github.com/asyncapi/cli/raw/master/test/fixtures/asyncapi_v1.yml
docker run --rm -it \
   --user=root \
   -v ${PWD}/asyncapi_v1.yml:/app/asyncapi.yml \
   -v ${PWD}/output:/app/output \
   asyncapi/cli generate fromTemplate -o /app/output /app/asyncapi.yml @asyncapi/html-template --force-write
```

Output
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[BABEL] Note: The code generator has deoptimised the styling of /usr/local/lib/node_modules/@asyncapi/cli/node_modules/@asyncapi/generator/node_modules/@asyncapi/html-template/template/js/asyncapi-ui.min.js as it exceeds the max of 500KB.
Generation in progress. Keep calm and wait a bit... done
Check out your shiny new generated files at /app/output.
```

The generated html is unexpectedly small
```
ls -al output | tr -s ' ' | cut -d' ' -f5- 

128 Nov 26 20:44 css
20934 Nov 26 20:55 index.html
96 Nov 26 20:44 js
```

An example of a generated faulty html is on the left, and an expected one on the right

<img width="1323" alt="Screenshot 2023-11-26 at 20 58 13" src="https://github.com/asyncapi/cli/assets/3178318/8e3eef24-a4cf-455b-9ac0-b508b46607cd">

**Comment by derberg** [comment]
@marcindulak sorry for late response, we were all busy releasing AsyncAPI v3

can you specify version of `@asyncapi/html-template` that you use? can be checked with `--debug` flag. Or just us it this way `@asyncapi/html-template@2.0.0` to make sure you use the latest one

**Comment by ldynia** [comment]
The template version was `2.0.0`.
I confirm that the above example is now working as expected, and the bug is gone.

**Comment by derberg** [comment]
Thanks a lot and sorry for the issues
