### ISSUE TITLE
Architecture refactor proposal

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/cli#99]
As the result of [the live stream](https://www.youtube.com/watch?v=wy1tRi8jt0A) @Souvikns and I did together discussing the CLI architecture, we came up with the following suggestion:

![Captura de pantalla 2021-10-18 a las 18 39 12](https://user-images.githubusercontent.com/242119/137772828-68315ff6-f05f-467f-bd29-67ae6a1c94d3.png)

1. OClif will do all the routing logic (yellow in the diagram).
2. All the commands logic should be on the command handlers (orange in the diagram).
3. We extract only 2 entities/models/services/call it whatever you prefer: SpecFile and Context. The first one helps us work with spec files (or even URLs in the future). The logic where we decide if we should read from the context or fall back to implicit names (asyncapi.[yaml,json,yml]) is encapsulated in the SpecFile entity, obviously relying on Context entity for any context-related operation.

We noticed that all commands are related to a specification file (existing or to be created), with the exception of:

- Removing a context
- Setting a context as the default one
- Renaming a context

_(and there may be others in the future)_

We acknowledge that this architecture is good enough for what we want right now because it's simple and straightforward. If it presents some challenges in the future, we'll look after them and decide if and how to re-architecture. Time will tell :)

**Comment by derberg** [comment]
Well done folks. Just go ahead!
